from ipyhop import State

state = State( 'init_state' )
rigid = State( 'rigid' )
rigid.object = {'camera1', 'waypoint0', 'waypoint3', 'objective1', 'rover0store', 'objective0', 'high_res', 'colour', 'waypoint1', 'low_res', 'rover1', 'waypoint2', 'rover0', 'general', 'rover1store', 'camera0'}
rigid.location = {'waypoint0', 'objective1', 'waypoint2', 'waypoint1', 'objective0', 'waypoint3'}
rigid.objective = {'objective1', 'objective0'}
rigid.store = {'rover0store', 'rover1store'}
rigid.waypoint = {'waypoint2', 'waypoint0', 'waypoint3', 'waypoint1'}
rigid.camera = {'camera1', 'camera0'}
rigid.mode = {'low_res', 'high_res', 'colour'}
rigid.rover = {'rover0', 'rover1'}
rigid.lander = {'general'}
rigid.visible = set( [('waypoint0', 'waypoint3'), ('waypoint1', 'waypoint2'), ('waypoint3', 'waypoint0'), ('waypoint2', 'waypoint1'), ('waypoint1', 'waypoint3'), ('waypoint2', 'waypoint3'), ('waypoint1', 'waypoint0'), ('waypoint3', 'waypoint2'), ('waypoint3', 'waypoint1'), ('waypoint2', 'waypoint0'), ('waypoint0', 'waypoint1'), ('waypoint0', 'waypoint2'), ] )
state.at_rock_sample = set( [('waypoint2',), ('waypoint0',), ('waypoint1',), ] )
state.at_soil_sample = set( [('waypoint2',), ] )
rigid.at_lander = set( [('general', 'waypoint0'), ] )
rigid.channel_free = set( [('general',), ] )
state.at = set( [('rover0', 'waypoint1'), ('rover1', 'waypoint3'), ] )
rigid.available = set( [('rover1',), ('rover0',), ] )
rigid.store_of = set( [('rover1store', 'rover1'), ('rover0store', 'rover0'), ] )
state.empty = set( [('rover0store',), ('rover1store',), ] )
rigid.equipped_for_soil_analysis = set( [('rover1',), ('rover0',), ] )
rigid.equipped_for_rock_analysis = set( [('rover1',), ('rover0',), ] )
rigid.equipped_for_imaging = set( [('rover1',), ('rover0',), ] )
rigid.can_traverse = set( [('rover0', 'waypoint3', 'waypoint1'), ('rover1', 'waypoint3', 'waypoint0'), ('rover0', 'waypoint1', 'waypoint3'), ('rover1', 'waypoint2', 'waypoint3'), ('rover0', 'waypoint1', 'waypoint0'), ('rover1', 'waypoint3', 'waypoint2'), ('rover1', 'waypoint0', 'waypoint1'), ('rover1', 'waypoint0', 'waypoint3'), ('rover0', 'waypoint0', 'waypoint1'), ('rover1', 'waypoint1', 'waypoint0'), ] )
rigid.on_board = set( [('camera0', 'rover0'), ('camera1', 'rover1'), ] )
rigid.calibration_target = set( [('camera0', 'objective1'), ('camera1', 'objective0'), ] )
rigid.supports = set( [('camera1', 'high_res'), ('camera1', 'low_res'), ('camera1', 'colour'), ('camera0', 'low_res'), ] )
rigid.visible_from = set( [('objective1', 'waypoint1'), ('objective0', 'waypoint0'), ('objective0', 'waypoint1'), ('objective1', 'waypoint0'), ] )
rigid.goal_communicated_soil_data = set( [('waypoint2',), ] )
rigid.goal_communicated_rock_data = set( [('waypoint0',), ] )
rigid.goal_communicated_image_data = set( [('objective0', 'colour'), ] )
state.have_image = set( [] )
state.full = set( [] )
state.have_soil_analysis = set( [] )
state.calibrated = set( [] )
state.communicated_rock_data = set( [] )
state.communicated_soil_data = set( [] )
state.have_rock_analysis = set( [] )
state.communicated_image_data = set( [] )

task_list = [('achieve_goals',)]
