from ipyhop import State

state = State( 'init_state' )
rigid = State( 'rigid' )
rigid.object = {'camera2', 'camera0', 'waypoint4', 'waypoint3', 'high_res', 'rover1', 'objective1', 'colour', 'rover0store', 'objective0', 'waypoint0', 'waypoint1', 'rover1store', 'low_res', 'waypoint2', 'camera1', 'waypoint5', 'rover0', 'general'}
rigid.rover = {'rover1', 'rover0'}
rigid.mode = {'low_res', 'high_res', 'colour'}
rigid.store = {'rover1store', 'rover0store'}
rigid.location = {'waypoint1', 'objective1', 'objective0', 'waypoint2', 'waypoint5', 'waypoint0', 'waypoint4', 'waypoint3'}
rigid.waypoint = {'waypoint1', 'waypoint2', 'waypoint5', 'waypoint0', 'waypoint4', 'waypoint3'}
rigid.objective = {'objective1', 'objective0'}
rigid.camera = {'camera0', 'camera1', 'camera2'}
rigid.lander = {'general'}
rigid.visible = set( [('waypoint1', 'waypoint4'), ('waypoint5', 'waypoint0'), ('waypoint4', 'waypoint1'), ('waypoint1', 'waypoint0'), ('waypoint3', 'waypoint5'), ('waypoint5', 'waypoint2'), ('waypoint0', 'waypoint2'), ('waypoint2', 'waypoint5'), ('waypoint0', 'waypoint1'), ('waypoint3', 'waypoint4'), ('waypoint3', 'waypoint0'), ('waypoint4', 'waypoint3'), ('waypoint2', 'waypoint0'), ('waypoint3', 'waypoint2'), ('waypoint5', 'waypoint3'), ('waypoint3', 'waypoint1'), ('waypoint0', 'waypoint3'), ('waypoint1', 'waypoint3'), ('waypoint2', 'waypoint3'), ('waypoint4', 'waypoint5'), ('waypoint0', 'waypoint5'), ('waypoint5', 'waypoint4'), ] )
state.at_rock_sample = set( [('waypoint3',), ('waypoint5',), ('waypoint2',), ('waypoint0',), ] )
state.at_soil_sample = set( [('waypoint5',), ('waypoint2',), ('waypoint1',), ('waypoint3',), ('waypoint4',), ] )
rigid.at_lander = set( [('general', 'waypoint3'), ] )
rigid.channel_free = set( [('general',), ] )
state.at = set( [('rover1', 'waypoint4'), ('rover0', 'waypoint1'), ] )
rigid.available = set( [('rover0',), ('rover1',), ] )
rigid.store_of = set( [('rover0store', 'rover0'), ('rover1store', 'rover1'), ] )
state.empty = set( [('rover1store',), ('rover0store',), ] )
rigid.equipped_for_rock_analysis = set( [('rover0',), ] )
rigid.equipped_for_imaging = set( [('rover0',), ('rover1',), ] )
rigid.can_traverse = set( [('rover0', 'waypoint0', 'waypoint5'), ('rover1', 'waypoint4', 'waypoint5'), ('rover0', 'waypoint4', 'waypoint1'), ('rover0', 'waypoint0', 'waypoint2'), ('rover0', 'waypoint5', 'waypoint0'), ('rover0', 'waypoint0', 'waypoint1'), ('rover0', 'waypoint1', 'waypoint4'), ('rover0', 'waypoint1', 'waypoint0'), ('rover0', 'waypoint2', 'waypoint0'), ('rover1', 'waypoint1', 'waypoint4'), ('rover1', 'waypoint0', 'waypoint1'), ('rover1', 'waypoint5', 'waypoint4'), ('rover1', 'waypoint4', 'waypoint1'), ('rover1', 'waypoint1', 'waypoint0'), ('rover0', 'waypoint0', 'waypoint3'), ('rover0', 'waypoint3', 'waypoint0'), ('rover1', 'waypoint2', 'waypoint5'), ('rover1', 'waypoint5', 'waypoint2'), ('rover1', 'waypoint4', 'waypoint3'), ('rover1', 'waypoint3', 'waypoint4'), ] )
rigid.equipped_for_soil_analysis = set( [('rover1',), ] )
rigid.on_board = set( [('camera2', 'rover1'), ('camera0', 'rover0'), ('camera1', 'rover0'), ] )
rigid.calibration_target = set( [('camera2', 'objective0'), ('camera0', 'objective0'), ('camera1', 'objective1'), ] )
rigid.supports = set( [('camera2', 'high_res'), ('camera0', 'low_res'), ('camera1', 'low_res'), ('camera0', 'colour'), ('camera1', 'colour'), ('camera2', 'colour'), ] )
rigid.visible_from = set( [('objective0', 'waypoint1'), ('objective0', 'waypoint3'), ('objective0', 'waypoint4'), ('objective1', 'waypoint1'), ('objective0', 'waypoint0'), ('objective0', 'waypoint5'), ('objective0', 'waypoint2'), ('objective1', 'waypoint0'), ] )
rigid.goal_communicated_soil_data = set( [('waypoint1',), ('waypoint2',), ('waypoint5',), ('waypoint4',), ] )
rigid.goal_communicated_rock_data = set( [('waypoint3',), ('waypoint2',), ('waypoint0',), ] )
rigid.goal_communicated_image_data = set( [('objective0', 'colour'), ('objective0', 'low_res'), ('objective1', 'low_res'), ] )
state.communicated_rock_data = set( [] )
state.have_rock_analysis = set( [] )
state.calibrated = set( [] )
state.communicated_image_data = set( [] )
state.have_image = set( [] )
state.have_soil_analysis = set( [] )
state.full = set( [] )
state.communicated_soil_data = set( [] )

task_list = [('achieve_goals',)]
