from ipyhop import State

state = State( 'init_state' )
rigid = State( 'rigid' )
rigid.location = {'waypoint0', 'waypoint4', 'waypoint1', 'waypoint3', 'waypoint2', 'objective1', 'objective0', 'waypoint5'}
rigid.objective = {'objective1', 'objective0'}
rigid.object = {'waypoint0', 'high_res', 'waypoint1', 'rover0', 'colour', 'low_res', 'objective0', 'general', 'rover1', 'camera1', 'rover2', 'waypoint5', 'rover1store', 'waypoint4', 'rover0store', 'waypoint3', 'waypoint2', 'camera0', 'rover2store', 'objective1'}
rigid.camera = {'camera1', 'camera0'}
rigid.lander = {'general'}
rigid.store = {'rover1store', 'rover2store', 'rover0store'}
rigid.waypoint = {'waypoint0', 'waypoint4', 'waypoint1', 'waypoint3', 'waypoint2', 'waypoint5'}
rigid.rover = {'rover0', 'rover1', 'rover2'}
rigid.mode = {'high_res', 'colour', 'low_res'}
rigid.visible = set( [('waypoint5', 'waypoint0'), ('waypoint3', 'waypoint0'), ('waypoint0', 'waypoint1'), ('waypoint1', 'waypoint5'), ('waypoint0', 'waypoint2'), ('waypoint2', 'waypoint5'), ('waypoint0', 'waypoint3'), ('waypoint5', 'waypoint1'), ('waypoint4', 'waypoint3'), ('waypoint5', 'waypoint2'), ('waypoint3', 'waypoint2'), ('waypoint1', 'waypoint0'), ('waypoint2', 'waypoint0'), ('waypoint0', 'waypoint4'), ('waypoint0', 'waypoint5'), ('waypoint2', 'waypoint1'), ('waypoint1', 'waypoint2'), ('waypoint5', 'waypoint4'), ('waypoint4', 'waypoint5'), ('waypoint3', 'waypoint4'), ('waypoint2', 'waypoint3'), ('waypoint4', 'waypoint0'), ] )
state.at_soil_sample = set( [('waypoint4',), ('waypoint1',), ] )
state.at_rock_sample = set( [('waypoint5',), ('waypoint3',), ('waypoint4',), ('waypoint2',), ] )
rigid.at_lander = set( [('general', 'waypoint3'), ] )
rigid.channel_free = set( [('general',), ] )
state.at = set( [('rover1', 'waypoint3'), ('rover2', 'waypoint4'), ('rover0', 'waypoint2'), ] )
rigid.available = set( [('rover1',), ('rover2',), ('rover0',), ] )
rigid.store_of = set( [('rover2store', 'rover2'), ('rover1store', 'rover1'), ('rover0store', 'rover0'), ] )
state.empty = set( [('rover2store',), ('rover0store',), ('rover1store',), ] )
rigid.equipped_for_soil_analysis = set( [('rover2',), ('rover0',), ] )
rigid.equipped_for_rock_analysis = set( [('rover1',), ('rover2',), ('rover0',), ] )
rigid.equipped_for_imaging = set( [('rover2',), ('rover0',), ] )
rigid.can_traverse = set( [('rover1', 'waypoint2', 'waypoint3'), ('rover2', 'waypoint0', 'waypoint3'), ('rover0', 'waypoint2', 'waypoint5'), ('rover2', 'waypoint3', 'waypoint0'), ('rover2', 'waypoint1', 'waypoint0'), ('rover2', 'waypoint2', 'waypoint5'), ('rover1', 'waypoint0', 'waypoint1'), ('rover1', 'waypoint3', 'waypoint0'), ('rover0', 'waypoint5', 'waypoint2'), ('rover0', 'waypoint3', 'waypoint2'), ('rover0', 'waypoint0', 'waypoint4'), ('rover0', 'waypoint2', 'waypoint0'), ('rover2', 'waypoint5', 'waypoint2'), ('rover1', 'waypoint0', 'waypoint3'), ('rover2', 'waypoint0', 'waypoint4'), ('rover1', 'waypoint5', 'waypoint0'), ('rover1', 'waypoint4', 'waypoint3'), ('rover0', 'waypoint1', 'waypoint2'), ('rover0', 'waypoint2', 'waypoint1'), ('rover1', 'waypoint3', 'waypoint2'), ('rover2', 'waypoint4', 'waypoint5'), ('rover1', 'waypoint1', 'waypoint0'), ('rover0', 'waypoint2', 'waypoint3'), ('rover2', 'waypoint5', 'waypoint4'), ('rover0', 'waypoint4', 'waypoint0'), ('rover1', 'waypoint0', 'waypoint5'), ('rover2', 'waypoint4', 'waypoint0'), ('rover1', 'waypoint3', 'waypoint4'), ('rover2', 'waypoint0', 'waypoint1'), ('rover0', 'waypoint0', 'waypoint2'), ] )
rigid.on_board = set( [('camera1', 'rover2'), ('camera0', 'rover0'), ] )
rigid.calibration_target = set( [('camera0', 'objective0'), ('camera1', 'objective1'), ] )
rigid.supports = set( [('camera0', 'high_res'), ('camera1', 'high_res'), ('camera0', 'colour'), ] )
rigid.visible_from = set( [('objective0', 'waypoint2'), ('objective1', 'waypoint0'), ('objective0', 'waypoint3'), ('objective1', 'waypoint2'), ('objective1', 'waypoint3'), ('objective0', 'waypoint4'), ('objective0', 'waypoint1'), ('objective1', 'waypoint1'), ('objective0', 'waypoint0'), ] )
rigid.goal_communicated_soil_data = set( [('waypoint4',), ('waypoint1',), ] )
rigid.goal_communicated_rock_data = set( [('waypoint3',), ('waypoint4',), ('waypoint2',), ] )
rigid.goal_communicated_image_data = set( [('objective0', 'high_res'), ] )
state.have_soil_analysis = set( [] )
state.communicated_rock_data = set( [] )
state.communicated_soil_data = set( [] )
state.communicated_image_data = set( [] )
state.have_image = set( [] )
state.full = set( [] )
state.have_rock_analysis = set( [] )
state.calibrated = set( [] )

task_list = [('achieve__goals',)]
