from ipyhop import State

state = State( 'init_state' )
rigid = State( 'rigid' )
rigid.object = {'camera0', 'rover2store', 'rover0store', 'objective1', 'waypoint1', 'waypoint5', 'camera1', 'high_res', 'waypoint4', 'rover2', 'low_res', 'colour', 'objective2', 'camera3', 'general', 'camera2', 'rover0', 'objective0', 'rover3store', 'rover3', 'waypoint0', 'waypoint2', 'rover1store', 'rover1', 'waypoint3'}
rigid.location = {'objective1', 'waypoint1', 'waypoint0', 'waypoint2', 'waypoint5', 'waypoint4', 'objective2', 'waypoint3', 'objective0'}
rigid.objective = {'objective1', 'objective2', 'objective0'}
rigid.waypoint = {'waypoint4', 'waypoint2', 'waypoint5', 'waypoint3', 'waypoint1', 'waypoint0'}
rigid.lander = {'general'}
rigid.mode = {'low_res', 'high_res', 'colour'}
rigid.store = {'rover2store', 'rover0store', 'rover3store', 'rover1store'}
rigid.rover = {'rover1', 'rover3', 'rover2', 'rover0'}
rigid.camera = {'camera0', 'camera2', 'camera3', 'camera1'}
rigid.visible = set( [('waypoint2', 'waypoint5'), ('waypoint2', 'waypoint1'), ('waypoint5', 'waypoint2'), ('waypoint3', 'waypoint2'), ('waypoint0', 'waypoint3'), ('waypoint0', 'waypoint4'), ('waypoint3', 'waypoint0'), ('waypoint1', 'waypoint5'), ('waypoint2', 'waypoint0'), ('waypoint4', 'waypoint1'), ('waypoint4', 'waypoint5'), ('waypoint5', 'waypoint3'), ('waypoint1', 'waypoint2'), ('waypoint5', 'waypoint4'), ('waypoint3', 'waypoint4'), ('waypoint1', 'waypoint0'), ('waypoint4', 'waypoint2'), ('waypoint2', 'waypoint3'), ('waypoint4', 'waypoint0'), ('waypoint0', 'waypoint1'), ('waypoint2', 'waypoint4'), ('waypoint1', 'waypoint4'), ('waypoint0', 'waypoint2'), ('waypoint4', 'waypoint3'), ('waypoint5', 'waypoint1'), ('waypoint3', 'waypoint5'), ] )
state.at_soil_sample = set( [('waypoint1',), ('waypoint3',), ('waypoint4',), ] )
state.at_rock_sample = set( [('waypoint2',), ('waypoint3',), ('waypoint4',), ('waypoint5',), ] )
rigid.at_lander = set( [('general', 'waypoint0'), ] )
rigid.channel_free = set( [('general',), ] )
state.at = set( [('rover3', 'waypoint3'), ('rover2', 'waypoint2'), ('rover0', 'waypoint2'), ('rover1', 'waypoint2'), ] )
rigid.available = set( [('rover3',), ('rover0',), ('rover1',), ('rover2',), ] )
rigid.store_of = set( [('rover1store', 'rover1'), ('rover2store', 'rover2'), ('rover0store', 'rover0'), ('rover3store', 'rover3'), ] )
state.empty = set( [('rover0store',), ('rover3store',), ('rover2store',), ('rover1store',), ] )
rigid.equipped_for_soil_analysis = set( [('rover3',), ('rover0',), ] )
rigid.equipped_for_rock_analysis = set( [('rover3',), ('rover0',), ('rover1',), ('rover2',), ] )
rigid.can_traverse = set( [('rover2', 'waypoint0', 'waypoint2'), ('rover3', 'waypoint0', 'waypoint1'), ('rover1', 'waypoint3', 'waypoint4'), ('rover2', 'waypoint2', 'waypoint1'), ('rover1', 'waypoint1', 'waypoint0'), ('rover2', 'waypoint2', 'waypoint5'), ('rover1', 'waypoint2', 'waypoint3'), ('rover3', 'waypoint4', 'waypoint3'), ('rover1', 'waypoint0', 'waypoint1'), ('rover0', 'waypoint2', 'waypoint3'), ('rover0', 'waypoint5', 'waypoint3'), ('rover0', 'waypoint2', 'waypoint4'), ('rover0', 'waypoint1', 'waypoint0'), ('rover0', 'waypoint0', 'waypoint1'), ('rover0', 'waypoint4', 'waypoint2'), ('rover2', 'waypoint5', 'waypoint2'), ('rover2', 'waypoint2', 'waypoint0'), ('rover2', 'waypoint3', 'waypoint0'), ('rover2', 'waypoint0', 'waypoint3'), ('rover1', 'waypoint0', 'waypoint2'), ('rover1', 'waypoint4', 'waypoint3'), ('rover3', 'waypoint2', 'waypoint5'), ('rover0', 'waypoint0', 'waypoint2'), ('rover0', 'waypoint3', 'waypoint5'), ('rover1', 'waypoint2', 'waypoint5'), ('rover3', 'waypoint0', 'waypoint3'), ('rover3', 'waypoint3', 'waypoint2'), ('rover3', 'waypoint5', 'waypoint2'), ('rover3', 'waypoint3', 'waypoint0'), ('rover2', 'waypoint2', 'waypoint4'), ('rover2', 'waypoint1', 'waypoint2'), ('rover1', 'waypoint5', 'waypoint2'), ('rover1', 'waypoint3', 'waypoint2'), ('rover2', 'waypoint4', 'waypoint2'), ('rover0', 'waypoint3', 'waypoint2'), ('rover1', 'waypoint2', 'waypoint0'), ('rover0', 'waypoint2', 'waypoint0'), ('rover3', 'waypoint1', 'waypoint0'), ('rover3', 'waypoint3', 'waypoint4'), ('rover3', 'waypoint2', 'waypoint3'), ] )
rigid.equipped_for_imaging = set( [('rover3',), ('rover1',), ('rover2',), ] )
rigid.on_board = set( [('camera3', 'rover2'), ('camera0', 'rover3'), ('camera2', 'rover1'), ('camera1', 'rover3'), ] )
rigid.calibration_target = set( [('camera1', 'objective0'), ('camera0', 'objective1'), ('camera2', 'objective0'), ('camera3', 'objective1'), ] )
rigid.supports = set( [('camera1', 'colour'), ('camera2', 'colour'), ('camera2', 'low_res'), ('camera2', 'high_res'), ('camera3', 'colour'), ('camera1', 'high_res'), ('camera0', 'colour'), ('camera3', 'low_res'), ('camera0', 'low_res'), ('camera0', 'high_res'), ] )
rigid.visible_from = set( [('objective2', 'waypoint0'), ('objective2', 'waypoint2'), ('objective2', 'waypoint1'), ('objective1', 'waypoint0'), ('objective0', 'waypoint2'), ('objective0', 'waypoint0'), ('objective0', 'waypoint1'), ] )
rigid.goal_communicated_soil_data = set( [('waypoint1',), ('waypoint3',), ('waypoint4',), ] )
rigid.goal_communicated_rock_data = set( [('waypoint4',), ('waypoint5',), ] )
rigid.goal_communicated_image_data = set( [('objective2', 'low_res'), ('objective0', 'low_res'), ('objective0', 'high_res'), ] )
state.communicated_soil_data = set( [] )
state.calibrated = set( [] )
state.full = set( [] )
state.communicated_rock_data = set( [] )
state.have_image = set( [] )
state.have_soil_analysis = set( [] )
state.have_rock_analysis = set( [] )
state.communicated_image_data = set( [] )

task_list = [('achieve__goals',)]
