from ipyhop import State

state = State( 'init_state' )
rigid = State( 'rigid' )
rigid.object = {'rover1', 'rover0', 'colour', 'rover2store', 'camera2', 'rover0store', 'waypoint5', 'camera0', 'waypoint4', 'waypoint3', 'camera1', 'camera3', 'low_res', 'rover3store', 'waypoint6', 'objective2', 'waypoint2', 'waypoint7', 'objective0', 'waypoint0', 'waypoint1', 'general', 'rover3', 'high_res', 'rover2', 'objective1', 'rover1store'}
rigid.location = {'objective2', 'waypoint6', 'waypoint2', 'waypoint7', 'objective0', 'waypoint0', 'waypoint1', 'waypoint4', 'waypoint3', 'objective1', 'waypoint5'}
rigid.rover = {'rover1', 'rover3', 'rover0', 'rover2'}
rigid.camera = {'camera3', 'camera1', 'camera2', 'camera0'}
rigid.lander = {'general'}
rigid.waypoint = {'waypoint6', 'waypoint2', 'waypoint7', 'waypoint0', 'waypoint1', 'waypoint4', 'waypoint3', 'waypoint5'}
rigid.objective = {'objective1', 'objective2', 'objective0'}
rigid.mode = {'low_res', 'high_res', 'colour'}
rigid.store = {'rover3store', 'rover2store', 'rover0store', 'rover1store'}
rigid.visible = set( [('waypoint2', 'waypoint3'), ('waypoint3', 'waypoint0'), ('waypoint4', 'waypoint5'), ('waypoint0', 'waypoint1'), ('waypoint1', 'waypoint7'), ('waypoint4', 'waypoint1'), ('waypoint0', 'waypoint3'), ('waypoint0', 'waypoint4'), ('waypoint3', 'waypoint6'), ('waypoint6', 'waypoint5'), ('waypoint6', 'waypoint4'), ('waypoint3', 'waypoint7'), ('waypoint1', 'waypoint5'), ('waypoint6', 'waypoint3'), ('waypoint6', 'waypoint2'), ('waypoint1', 'waypoint2'), ('waypoint1', 'waypoint3'), ('waypoint1', 'waypoint4'), ('waypoint3', 'waypoint5'), ('waypoint7', 'waypoint0'), ('waypoint3', 'waypoint1'), ('waypoint3', 'waypoint2'), ('waypoint7', 'waypoint5'), ('waypoint7', 'waypoint1'), ('waypoint7', 'waypoint2'), ('waypoint5', 'waypoint6'), ('waypoint7', 'waypoint3'), ('waypoint5', 'waypoint7'), ('waypoint2', 'waypoint6'), ('waypoint2', 'waypoint7'), ('waypoint5', 'waypoint1'), ('waypoint4', 'waypoint0'), ('waypoint5', 'waypoint2'), ('waypoint5', 'waypoint3'), ('waypoint5', 'waypoint4'), ('waypoint6', 'waypoint0'), ('waypoint0', 'waypoint6'), ('waypoint4', 'waypoint6'), ('waypoint2', 'waypoint5'), ('waypoint2', 'waypoint1'), ('waypoint0', 'waypoint7'), ('waypoint1', 'waypoint0'), ] )
state.at_soil_sample = set( [('waypoint0',), ('waypoint6',), ('waypoint1',), ('waypoint3',), ] )
state.at_rock_sample = set( [('waypoint7',), ('waypoint4',), ('waypoint1',), ('waypoint0',), ('waypoint2',), ('waypoint6',), ] )
rigid.at_lander = set( [('general', 'waypoint1'), ] )
rigid.channel_free = set( [('general',), ] )
state.at = set( [('rover0', 'waypoint1'), ('rover1', 'waypoint3'), ('rover2', 'waypoint3'), ('rover3', 'waypoint7'), ] )
rigid.available = set( [('rover3',), ('rover1',), ('rover2',), ('rover0',), ] )
rigid.store_of = set( [('rover3store', 'rover3'), ('rover0store', 'rover0'), ('rover1store', 'rover1'), ('rover2store', 'rover2'), ] )
state.empty = set( [('rover3store',), ('rover0store',), ('rover1store',), ('rover2store',), ] )
rigid.equipped_for_soil_analysis = set( [('rover3',), ('rover1',), ('rover2',), ('rover0',), ] )
rigid.equipped_for_imaging = set( [('rover3',), ('rover1',), ('rover2',), ('rover0',), ] )
rigid.can_traverse = set( [('rover1', 'waypoint6', 'waypoint4'), ('rover2', 'waypoint4', 'waypoint0'), ('rover3', 'waypoint5', 'waypoint7'), ('rover2', 'waypoint5', 'waypoint3'), ('rover1', 'waypoint3', 'waypoint0'), ('rover1', 'waypoint1', 'waypoint7'), ('rover0', 'waypoint4', 'waypoint1'), ('rover1', 'waypoint3', 'waypoint7'), ('rover2', 'waypoint2', 'waypoint3'), ('rover2', 'waypoint0', 'waypoint3'), ('rover2', 'waypoint0', 'waypoint4'), ('rover2', 'waypoint6', 'waypoint3'), ('rover2', 'waypoint3', 'waypoint0'), ('rover0', 'waypoint1', 'waypoint5'), ('rover3', 'waypoint0', 'waypoint7'), ('rover2', 'waypoint3', 'waypoint6'), ('rover0', 'waypoint1', 'waypoint4'), ('rover0', 'waypoint3', 'waypoint1'), ('rover0', 'waypoint1', 'waypoint3'), ('rover3', 'waypoint4', 'waypoint0'), ('rover3', 'waypoint6', 'waypoint3'), ('rover2', 'waypoint3', 'waypoint7'), ('rover0', 'waypoint7', 'waypoint0'), ('rover0', 'waypoint3', 'waypoint2'), ('rover1', 'waypoint7', 'waypoint1'), ('rover3', 'waypoint2', 'waypoint1'), ('rover2', 'waypoint3', 'waypoint5'), ('rover2', 'waypoint3', 'waypoint1'), ('rover2', 'waypoint1', 'waypoint3'), ('rover1', 'waypoint7', 'waypoint2'), ('rover1', 'waypoint7', 'waypoint3'), ('rover3', 'waypoint0', 'waypoint4'), ('rover3', 'waypoint3', 'waypoint6'), ('rover2', 'waypoint3', 'waypoint2'), ('rover3', 'waypoint7', 'waypoint0'), ('rover3', 'waypoint3', 'waypoint7'), ('rover3', 'waypoint1', 'waypoint7'), ('rover2', 'waypoint7', 'waypoint3'), ('rover1', 'waypoint5', 'waypoint6'), ('rover3', 'waypoint7', 'waypoint5'), ('rover1', 'waypoint6', 'waypoint0'), ('rover3', 'waypoint7', 'waypoint1'), ('rover0', 'waypoint6', 'waypoint0'), ('rover0', 'waypoint0', 'waypoint6'), ('rover3', 'waypoint1', 'waypoint2'), ('rover1', 'waypoint0', 'waypoint6'), ('rover3', 'waypoint7', 'waypoint3'), ('rover1', 'waypoint2', 'waypoint7'), ('rover0', 'waypoint5', 'waypoint1'), ('rover0', 'waypoint0', 'waypoint7'), ('rover0', 'waypoint0', 'waypoint1'), ('rover1', 'waypoint4', 'waypoint6'), ('rover1', 'waypoint0', 'waypoint3'), ('rover1', 'waypoint6', 'waypoint5'), ('rover0', 'waypoint1', 'waypoint0'), ('rover0', 'waypoint2', 'waypoint3'), ] )
rigid.equipped_for_rock_analysis = set( [('rover1',), ] )
rigid.on_board = set( [('camera2', 'rover3'), ('camera0', 'rover1'), ('camera3', 'rover0'), ('camera1', 'rover2'), ] )
rigid.calibration_target = set( [('camera2', 'objective0'), ('camera0', 'objective1'), ('camera3', 'objective1'), ('camera1', 'objective0'), ] )
rigid.supports = set( [('camera0', 'high_res'), ('camera2', 'high_res'), ('camera0', 'low_res'), ('camera1', 'colour'), ('camera3', 'colour'), ('camera1', 'high_res'), ] )
rigid.visible_from = set( [('objective1', 'waypoint1'), ('objective2', 'waypoint4'), ('objective2', 'waypoint6'), ('objective1', 'waypoint0'), ('objective1', 'waypoint2'), ('objective0', 'waypoint0'), ('objective0', 'waypoint5'), ('objective0', 'waypoint1'), ('objective2', 'waypoint5'), ('objective0', 'waypoint2'), ('objective0', 'waypoint3'), ('objective0', 'waypoint4'), ('objective2', 'waypoint1'), ('objective2', 'waypoint0'), ('objective2', 'waypoint2'), ('objective2', 'waypoint3'), ] )
rigid.goal_communicated_soil_data = set( [('waypoint0',), ('waypoint3',), ('waypoint1',), ('waypoint6',), ] )
rigid.goal_communicated_rock_data = set( [('waypoint0',), ('waypoint7',), ('waypoint6',), ('waypoint4',), ] )
rigid.goal_communicated_image_data = set( [('objective1', 'high_res'), ] )
state.have_rock_analysis = set( [] )
state.communicated_image_data = set( [] )
state.communicated_soil_data = set( [] )
state.have_image = set( [] )
state.calibrated = set( [] )
state.full = set( [] )
state.have_soil_analysis = set( [] )
state.communicated_rock_data = set( [] )

task_list = [('achieve__goals',)]
