from ipyhop import State

state = State( 'init_state' )
rigid = State( 'rigid' )
rigid.object = {'low_res', 'waypoint8', 'camera3', 'waypoint6', 'rover0store', 'objective3', 'high_res', 'camera1', 'waypoint4', 'waypoint3', 'rover2store', 'rover3', 'waypoint5', 'rover2', 'objective0', 'general', 'waypoint2', 'colour', 'rover0', 'rover3store', 'waypoint1', 'camera0', 'objective1', 'camera2', 'rover1store', 'rover1', 'objective2', 'waypoint7', 'camera4', 'waypoint0'}
rigid.camera = {'camera2', 'camera3', 'camera1', 'camera4', 'camera0'}
rigid.mode = {'low_res', 'high_res', 'colour'}
rigid.location = {'waypoint2', 'waypoint8', 'waypoint6', 'waypoint4', 'objective3', 'waypoint1', 'objective1', 'waypoint3', 'waypoint5', 'objective2', 'waypoint7', 'objective0', 'waypoint0'}
rigid.waypoint = {'waypoint2', 'waypoint8', 'waypoint6', 'waypoint4', 'waypoint1', 'waypoint3', 'waypoint5', 'waypoint7', 'waypoint0'}
rigid.lander = {'general'}
rigid.rover = {'rover0', 'rover1', 'rover2', 'rover3'}
rigid.store = {'rover3store', 'rover2store', 'rover1store', 'rover0store'}
rigid.objective = {'objective3', 'objective2', 'objective0', 'objective1'}
rigid.visible = set( [('waypoint8', 'waypoint2'), ('waypoint2', 'waypoint5'), ('waypoint3', 'waypoint4'), ('waypoint5', 'waypoint1'), ('waypoint4', 'waypoint3'), ('waypoint4', 'waypoint0'), ('waypoint2', 'waypoint1'), ('waypoint1', 'waypoint5'), ('waypoint8', 'waypoint3'), ('waypoint7', 'waypoint1'), ('waypoint8', 'waypoint7'), ('waypoint3', 'waypoint5'), ('waypoint0', 'waypoint4'), ('waypoint5', 'waypoint2'), ('waypoint3', 'waypoint1'), ('waypoint2', 'waypoint8'), ('waypoint0', 'waypoint5'), ('waypoint7', 'waypoint2'), ('waypoint6', 'waypoint2'), ('waypoint1', 'waypoint8'), ('waypoint1', 'waypoint2'), ('waypoint2', 'waypoint6'), ('waypoint7', 'waypoint8'), ('waypoint5', 'waypoint0'), ('waypoint0', 'waypoint1'), ('waypoint5', 'waypoint3'), ('waypoint2', 'waypoint0'), ('waypoint8', 'waypoint4'), ('waypoint3', 'waypoint8'), ('waypoint2', 'waypoint7'), ('waypoint7', 'waypoint6'), ('waypoint6', 'waypoint0'), ('waypoint7', 'waypoint3'), ('waypoint1', 'waypoint0'), ('waypoint1', 'waypoint3'), ('waypoint7', 'waypoint0'), ('waypoint6', 'waypoint7'), ('waypoint1', 'waypoint7'), ('waypoint0', 'waypoint2'), ('waypoint3', 'waypoint0'), ('waypoint4', 'waypoint1'), ('waypoint3', 'waypoint7'), ('waypoint8', 'waypoint1'), ('waypoint0', 'waypoint6'), ('waypoint2', 'waypoint4'), ('waypoint0', 'waypoint3'), ('waypoint0', 'waypoint7'), ('waypoint4', 'waypoint2'), ('waypoint1', 'waypoint4'), ('waypoint4', 'waypoint8'), ] )
state.at_rock_sample = set( [('waypoint6',), ('waypoint0',), ('waypoint7',), ('waypoint8',), ('waypoint2',), ('waypoint4',), ('waypoint1',), ] )
state.at_soil_sample = set( [('waypoint7',), ('waypoint2',), ('waypoint4',), ('waypoint5',), ] )
rigid.at_lander = set( [('general', 'waypoint2'), ] )
rigid.channel_free = set( [('general',), ] )
state.at = set( [('rover1', 'waypoint6'), ('rover2', 'waypoint6'), ('rover0', 'waypoint7'), ('rover3', 'waypoint3'), ] )
rigid.available = set( [('rover1',), ('rover3',), ('rover2',), ('rover0',), ] )
rigid.store_of = set( [('rover0store', 'rover0'), ('rover1store', 'rover1'), ('rover2store', 'rover2'), ('rover3store', 'rover3'), ] )
state.empty = set( [('rover2store',), ('rover0store',), ('rover3store',), ('rover1store',), ] )
rigid.equipped_for_soil_analysis = set( [('rover1',), ('rover3',), ('rover2',), ('rover0',), ] )
rigid.equipped_for_imaging = set( [('rover1',), ('rover3',), ('rover2',), ('rover0',), ] )
rigid.can_traverse = set( [('rover2', 'waypoint2', 'waypoint8'), ('rover3', 'waypoint0', 'waypoint6'), ('rover0', 'waypoint0', 'waypoint6'), ('rover3', 'waypoint0', 'waypoint3'), ('rover3', 'waypoint3', 'waypoint0'), ('rover2', 'waypoint0', 'waypoint5'), ('rover0', 'waypoint0', 'waypoint7'), ('rover2', 'waypoint6', 'waypoint2'), ('rover0', 'waypoint4', 'waypoint2'), ('rover2', 'waypoint2', 'waypoint6'), ('rover3', 'waypoint3', 'waypoint7'), ('rover2', 'waypoint0', 'waypoint1'), ('rover1', 'waypoint2', 'waypoint8'), ('rover3', 'waypoint8', 'waypoint3'), ('rover0', 'waypoint8', 'waypoint7'), ('rover2', 'waypoint6', 'waypoint0'), ('rover0', 'waypoint5', 'waypoint1'), ('rover2', 'waypoint5', 'waypoint0'), ('rover3', 'waypoint2', 'waypoint1'), ('rover0', 'waypoint1', 'waypoint5'), ('rover2', 'waypoint6', 'waypoint7'), ('rover3', 'waypoint4', 'waypoint0'), ('rover1', 'waypoint2', 'waypoint0'), ('rover1', 'waypoint3', 'waypoint1'), ('rover2', 'waypoint3', 'waypoint0'), ('rover2', 'waypoint7', 'waypoint6'), ('rover0', 'waypoint7', 'waypoint1'), ('rover3', 'waypoint0', 'waypoint4'), ('rover2', 'waypoint1', 'waypoint0'), ('rover2', 'waypoint8', 'waypoint2'), ('rover1', 'waypoint7', 'waypoint0'), ('rover1', 'waypoint6', 'waypoint0'), ('rover0', 'waypoint3', 'waypoint1'), ('rover2', 'waypoint0', 'waypoint6'), ('rover1', 'waypoint0', 'waypoint2'), ('rover2', 'waypoint0', 'waypoint3'), ('rover3', 'waypoint3', 'waypoint5'), ('rover0', 'waypoint7', 'waypoint2'), ('rover0', 'waypoint2', 'waypoint7'), ('rover1', 'waypoint1', 'waypoint3'), ('rover3', 'waypoint1', 'waypoint2'), ('rover0', 'waypoint6', 'waypoint0'), ('rover0', 'waypoint7', 'waypoint8'), ('rover1', 'waypoint8', 'waypoint2'), ('rover3', 'waypoint5', 'waypoint3'), ('rover3', 'waypoint3', 'waypoint1'), ('rover1', 'waypoint2', 'waypoint4'), ('rover1', 'waypoint0', 'waypoint6'), ('rover1', 'waypoint0', 'waypoint3'), ('rover1', 'waypoint3', 'waypoint0'), ('rover1', 'waypoint4', 'waypoint2'), ('rover2', 'waypoint4', 'waypoint0'), ('rover0', 'waypoint1', 'waypoint3'), ('rover3', 'waypoint1', 'waypoint3'), ('rover3', 'waypoint7', 'waypoint3'), ('rover0', 'waypoint7', 'waypoint0'), ('rover1', 'waypoint0', 'waypoint7'), ('rover3', 'waypoint6', 'waypoint0'), ('rover0', 'waypoint1', 'waypoint7'), ('rover3', 'waypoint3', 'waypoint8'), ('rover0', 'waypoint2', 'waypoint4'), ('rover2', 'waypoint0', 'waypoint4'), ] )
rigid.equipped_for_rock_analysis = set( [('rover2',), ('rover3',), ] )
rigid.on_board = set( [('camera3', 'rover1'), ('camera0', 'rover2'), ('camera4', 'rover0'), ('camera2', 'rover3'), ('camera1', 'rover2'), ] )
rigid.calibration_target = set( [('camera0', 'objective1'), ('camera1', 'objective1'), ('camera2', 'objective1'), ('camera4', 'objective1'), ('camera3', 'objective2'), ] )
rigid.supports = set( [('camera4', 'low_res'), ('camera3', 'colour'), ('camera4', 'high_res'), ('camera1', 'colour'), ('camera0', 'high_res'), ('camera3', 'low_res'), ('camera1', 'low_res'), ('camera2', 'high_res'), ('camera0', 'colour'), ] )
rigid.visible_from = set( [('objective1', 'waypoint3'), ('objective3', 'waypoint5'), ('objective1', 'waypoint0'), ('objective1', 'waypoint7'), ('objective3', 'waypoint1'), ('objective2', 'waypoint2'), ('objective3', 'waypoint2'), ('objective2', 'waypoint0'), ('objective2', 'waypoint3'), ('objective1', 'waypoint4'), ('objective3', 'waypoint6'), ('objective3', 'waypoint0'), ('objective3', 'waypoint3'), ('objective1', 'waypoint5'), ('objective3', 'waypoint7'), ('objective1', 'waypoint1'), ('objective2', 'waypoint4'), ('objective1', 'waypoint2'), ('objective0', 'waypoint0'), ('objective2', 'waypoint5'), ('objective1', 'waypoint6'), ('objective3', 'waypoint4'), ('objective2', 'waypoint1'), ] )
rigid.goal_communicated_soil_data = set( [('waypoint7',), ('waypoint2',), ('waypoint4',), ('waypoint5',), ] )
rigid.goal_communicated_rock_data = set( [('waypoint6',), ('waypoint7',), ('waypoint8',), ('waypoint4',), ('waypoint1',), ] )
rigid.goal_communicated_image_data = set( [('objective2', 'high_res'), ('objective1', 'high_res'), ('objective3', 'high_res'), ] )
state.have_rock_analysis = set( [] )
state.communicated_rock_data = set( [] )
state.have_image = set( [] )
state.have_soil_analysis = set( [] )
state.full = set( [] )
state.communicated_soil_data = set( [] )
state.calibrated = set( [] )
state.communicated_image_data = set( [] )

task_list = [('achieve__goals',)]
