from ipyhop import State

state = State( 'init_state' )
rigid = State( 'rigid' )
rigid.location = {'waypoint0', 'waypoint9', 'waypoint4', 'waypoint1', 'objective3', 'waypoint3', 'waypoint2', 'objective2', 'waypoint8', 'objective1', 'waypoint6', 'objective0', 'waypoint5', 'waypoint7'}
rigid.objective = {'objective1', 'objective2', 'objective3', 'objective0'}
rigid.object = {'waypoint0', 'high_res', 'waypoint1', 'rover3', 'objective3', 'waypoint8', 'rover0', 'colour', 'low_res', 'objective0', 'rover3store', 'rover1', 'camera1', 'general', 'rover2', 'waypoint5', 'waypoint7', 'waypoint9', 'rover1store', 'waypoint4', 'rover0store', 'waypoint3', 'waypoint2', 'camera0', 'objective2', 'camera4', 'rover2store', 'camera2', 'objective1', 'waypoint6', 'camera3'}
rigid.camera = {'camera1', 'camera0', 'camera3', 'camera4', 'camera2'}
rigid.lander = {'general'}
rigid.store = {'rover1store', 'rover2store', 'rover0store', 'rover3store'}
rigid.waypoint = {'waypoint0', 'waypoint9', 'waypoint4', 'waypoint1', 'waypoint3', 'waypoint2', 'waypoint8', 'waypoint6', 'waypoint5', 'waypoint7'}
rigid.rover = {'rover0', 'rover1', 'rover2', 'rover3'}
rigid.mode = {'high_res', 'colour', 'low_res'}
rigid.visible = set( [('waypoint1', 'waypoint4'), ('waypoint3', 'waypoint7'), ('waypoint2', 'waypoint4'), ('waypoint3', 'waypoint0'), ('waypoint8', 'waypoint6'), ('waypoint1', 'waypoint5'), ('waypoint6', 'waypoint4'), ('waypoint9', 'waypoint4'), ('waypoint8', 'waypoint7'), ('waypoint4', 'waypoint1'), ('waypoint2', 'waypoint5'), ('waypoint6', 'waypoint5'), ('waypoint0', 'waypoint3'), ('waypoint7', 'waypoint5'), ('waypoint4', 'waypoint2'), ('waypoint7', 'waypoint8'), ('waypoint5', 'waypoint1'), ('waypoint1', 'waypoint6'), ('waypoint2', 'waypoint6'), ('waypoint0', 'waypoint9'), ('waypoint8', 'waypoint1'), ('waypoint5', 'waypoint2'), ('waypoint1', 'waypoint8'), ('waypoint3', 'waypoint2'), ('waypoint5', 'waypoint3'), ('waypoint4', 'waypoint9'), ('waypoint1', 'waypoint7'), ('waypoint9', 'waypoint6'), ('waypoint7', 'waypoint1'), ('waypoint6', 'waypoint8'), ('waypoint6', 'waypoint0'), ('waypoint9', 'waypoint8'), ('waypoint3', 'waypoint9'), ('waypoint0', 'waypoint4'), ('waypoint9', 'waypoint0'), ('waypoint7', 'waypoint3'), ('waypoint8', 'waypoint9'), ('waypoint2', 'waypoint1'), ('waypoint6', 'waypoint1'), ('waypoint1', 'waypoint2'), ('waypoint5', 'waypoint4'), ('waypoint4', 'waypoint5'), ('waypoint2', 'waypoint3'), ('waypoint6', 'waypoint2'), ('waypoint0', 'waypoint6'), ('waypoint9', 'waypoint2'), ('waypoint3', 'waypoint5'), ('waypoint6', 'waypoint3'), ('waypoint8', 'waypoint4'), ('waypoint9', 'waypoint3'), ('waypoint2', 'waypoint9'), ('waypoint4', 'waypoint6'), ('waypoint6', 'waypoint9'), ('waypoint4', 'waypoint8'), ('waypoint5', 'waypoint6'), ('waypoint3', 'waypoint6'), ('waypoint4', 'waypoint0'), ('waypoint5', 'waypoint7'), ] )
state.at_rock_sample = set( [('waypoint3',), ('waypoint4',), ('waypoint1',), ('waypoint8',), ('waypoint5',), ] )
state.at_soil_sample = set( [('waypoint9',), ('waypoint3',), ('waypoint4',), ('waypoint6',), ] )
rigid.at_lander = set( [('general', 'waypoint7'), ] )
rigid.channel_free = set( [('general',), ] )
state.at = set( [('rover1', 'waypoint4'), ('rover0', 'waypoint1'), ('rover3', 'waypoint2'), ('rover2', 'waypoint0'), ] )
rigid.available = set( [('rover1',), ('rover2',), ('rover3',), ('rover0',), ] )
rigid.store_of = set( [('rover3store', 'rover3'), ('rover2store', 'rover2'), ('rover1store', 'rover1'), ('rover0store', 'rover0'), ] )
state.empty = set( [('rover2store',), ('rover0store',), ('rover3store',), ('rover1store',), ] )
rigid.equipped_for_soil_analysis = set( [('rover1',), ('rover0',), ] )
rigid.equipped_for_imaging = set( [('rover1',), ('rover2',), ('rover3',), ('rover0',), ] )
rigid.can_traverse = set( [('rover1', 'waypoint5', 'waypoint4'), ('rover1', 'waypoint4', 'waypoint6'), ('rover3', 'waypoint7', 'waypoint1'), ('rover2', 'waypoint0', 'waypoint3'), ('rover2', 'waypoint3', 'waypoint0'), ('rover3', 'waypoint6', 'waypoint0'), ('rover0', 'waypoint8', 'waypoint7'), ('rover1', 'waypoint4', 'waypoint0'), ('rover0', 'waypoint1', 'waypoint6'), ('rover3', 'waypoint1', 'waypoint2'), ('rover0', 'waypoint7', 'waypoint8'), ('rover3', 'waypoint6', 'waypoint8'), ('rover2', 'waypoint0', 'waypoint9'), ('rover0', 'waypoint1', 'waypoint8'), ('rover0', 'waypoint4', 'waypoint9'), ('rover3', 'waypoint2', 'waypoint1'), ('rover1', 'waypoint3', 'waypoint0'), ('rover3', 'waypoint0', 'waypoint6'), ('rover3', 'waypoint9', 'waypoint2'), ('rover1', 'waypoint7', 'waypoint5'), ('rover0', 'waypoint8', 'waypoint1'), ('rover1', 'waypoint9', 'waypoint4'), ('rover0', 'waypoint3', 'waypoint2'), ('rover1', 'waypoint5', 'waypoint7'), ('rover0', 'waypoint0', 'waypoint4'), ('rover2', 'waypoint9', 'waypoint0'), ('rover3', 'waypoint6', 'waypoint2'), ('rover1', 'waypoint2', 'waypoint4'), ('rover1', 'waypoint0', 'waypoint3'), ('rover1', 'waypoint8', 'waypoint6'), ('rover2', 'waypoint3', 'waypoint2'), ('rover2', 'waypoint0', 'waypoint4'), ('rover1', 'waypoint4', 'waypoint2'), ('rover3', 'waypoint6', 'waypoint3'), ('rover1', 'waypoint6', 'waypoint4'), ('rover3', 'waypoint2', 'waypoint9'), ('rover2', 'waypoint6', 'waypoint0'), ('rover0', 'waypoint4', 'waypoint5'), ('rover3', 'waypoint1', 'waypoint4'), ('rover0', 'waypoint1', 'waypoint2'), ('rover0', 'waypoint2', 'waypoint1'), ('rover2', 'waypoint4', 'waypoint5'), ('rover1', 'waypoint4', 'waypoint9'), ('rover0', 'waypoint6', 'waypoint1'), ('rover3', 'waypoint3', 'waypoint6'), ('rover3', 'waypoint1', 'waypoint5'), ('rover2', 'waypoint0', 'waypoint6'), ('rover1', 'waypoint2', 'waypoint1'), ('rover0', 'waypoint5', 'waypoint4'), ('rover0', 'waypoint2', 'waypoint3'), ('rover1', 'waypoint0', 'waypoint4'), ('rover3', 'waypoint8', 'waypoint6'), ('rover2', 'waypoint5', 'waypoint4'), ('rover2', 'waypoint2', 'waypoint3'), ('rover0', 'waypoint4', 'waypoint0'), ('rover1', 'waypoint6', 'waypoint8'), ('rover3', 'waypoint4', 'waypoint1'), ('rover2', 'waypoint1', 'waypoint4'), ('rover2', 'waypoint4', 'waypoint8'), ('rover2', 'waypoint4', 'waypoint0'), ('rover3', 'waypoint1', 'waypoint7'), ('rover2', 'waypoint8', 'waypoint4'), ('rover1', 'waypoint4', 'waypoint5'), ('rover1', 'waypoint1', 'waypoint2'), ('rover3', 'waypoint5', 'waypoint1'), ('rover0', 'waypoint1', 'waypoint4'), ('rover3', 'waypoint2', 'waypoint6'), ('rover0', 'waypoint4', 'waypoint1'), ('rover0', 'waypoint9', 'waypoint4'), ('rover2', 'waypoint4', 'waypoint1'), ] )
rigid.equipped_for_rock_analysis = set( [('rover1',), ] )
rigid.on_board = set( [('camera1', 'rover2'), ('camera4', 'rover0'), ('camera0', 'rover3'), ('camera2', 'rover1'), ('camera3', 'rover1'), ] )
rigid.calibration_target = set( [('camera0', 'objective2'), ('camera3', 'objective0'), ('camera1', 'objective3'), ('camera2', 'objective3'), ('camera4', 'objective3'), ] )
rigid.supports = set( [('camera0', 'low_res'), ('camera2', 'low_res'), ('camera3', 'colour'), ('camera1', 'colour'), ('camera4', 'colour'), ('camera4', 'low_res'), ('camera3', 'low_res'), ('camera0', 'colour'), ] )
rigid.visible_from = set( [('objective1', 'waypoint5'), ('objective3', 'waypoint5'), ('objective2', 'waypoint1'), ('objective2', 'waypoint2'), ('objective3', 'waypoint6'), ('objective2', 'waypoint3'), ('objective0', 'waypoint1'), ('objective1', 'waypoint6'), ('objective0', 'waypoint2'), ('objective1', 'waypoint0'), ('objective3', 'waypoint0'), ('objective0', 'waypoint3'), ('objective2', 'waypoint4'), ('objective1', 'waypoint1'), ('objective3', 'waypoint1'), ('objective3', 'waypoint2'), ('objective3', 'waypoint3'), ('objective1', 'waypoint2'), ('objective2', 'waypoint5'), ('objective1', 'waypoint3'), ('objective0', 'waypoint4'), ('objective0', 'waypoint5'), ('objective2', 'waypoint6'), ('objective2', 'waypoint7'), ('objective2', 'waypoint8'), ('objective2', 'waypoint0'), ('objective0', 'waypoint6'), ('objective3', 'waypoint4'), ('objective1', 'waypoint4'), ('objective0', 'waypoint0'), ] )
rigid.goal_communicated_soil_data = set( [('waypoint3',), ('waypoint6',), ] )
rigid.goal_communicated_rock_data = set( [('waypoint4',), ('waypoint5',), ('waypoint8',), ] )
rigid.goal_communicated_image_data = set( [('objective0', 'colour'), ('objective0', 'low_res'), ('objective2', 'low_res'), ] )
state.have_soil_analysis = set( [] )
state.communicated_rock_data = set( [] )
state.communicated_soil_data = set( [] )
state.communicated_image_data = set( [] )
state.have_image = set( [] )
state.full = set( [] )
state.have_rock_analysis = set( [] )
state.calibrated = set( [] )

task_list = [('achieve__goals',)]
