from ipyhop import State

state = State( 'init_state' )
rigid = State( 'rigid' )
rigid.object = {'image2', 'groundstation2', 'phenomenon5', 'satellite3', 'phenomenon12', 'thermograph0', 'star9', 'phenomenon7', 'instrument9', 'star19', 'phenomenon18', 'instrument2', 'thermograph3', 'satellite2', 'planet16', 'instrument4', 'groundstation0', 'planet21', 'star22', 'image1', 'satellite5', 'star20', 'phenomenon6', 'star14', 'planet15', 'star10', 'instrument0', 'groundstation1', 'instrument11', 'groundstation4', 'satellite0', 'star24', 'instrument8', 'instrument5', 'instrument1', 'instrument6', 'phenomenon13', 'planet23', 'planet8', 'instrument3', 'instrument10', 'phenomenon11', 'planet17', 'instrument7', 'groundstation3', 'thermograph4', 'satellite1', 'satellite4'}
rigid.mode = {'thermograph0', 'image2', 'image1', 'thermograph4', 'thermograph3'}
rigid.instrument = {'instrument1', 'instrument2', 'instrument6', 'instrument0', 'instrument3', 'instrument10', 'instrument4', 'instrument7', 'instrument11', 'instrument9', 'instrument8', 'instrument5'}
rigid.satellite = {'satellite5', 'satellite0', 'satellite3', 'satellite1', 'satellite2', 'satellite4'}
rigid.direction = {'star20', 'phenomenon6', 'star14', 'planet15', 'star10', 'groundstation2', 'phenomenon5', 'phenomenon12', 'groundstation1', 'groundstation4', 'star9', 'phenomenon7', 'star24', 'star19', 'phenomenon18', 'phenomenon13', 'planet23', 'planet8', 'planet16', 'phenomenon11', 'planet17', 'groundstation0', 'planet21', 'star22', 'groundstation3'}
rigid.supports = set( [('instrument4', 'thermograph4'), ('instrument8', 'thermograph0'), ('instrument3', 'image2'), ('instrument0', 'thermograph0'), ('instrument6', 'thermograph3'), ('instrument3', 'thermograph0'), ('instrument11', 'image2'), ('instrument9', 'image2'), ('instrument2', 'thermograph3'), ('instrument11', 'thermograph0'), ('instrument9', 'thermograph0'), ('instrument6', 'image1'), ('instrument10', 'thermograph3'), ('instrument0', 'image1'), ('instrument2', 'image1'), ('instrument8', 'thermograph4'), ('instrument2', 'thermograph4'), ('instrument1', 'image2'), ('instrument10', 'image1'), ('instrument3', 'thermograph4'), ('instrument5', 'thermograph4'), ('instrument9', 'image1'), ('instrument7', 'image2'), ('instrument4', 'thermograph0'), ('instrument1', 'thermograph3'), ('instrument7', 'thermograph3'), ('instrument4', 'image1'), ] )
rigid.calibration_target = set( [('instrument1', 'groundstation0'), ('instrument9', 'groundstation2'), ('instrument4', 'groundstation1'), ('instrument8', 'groundstation2'), ('instrument7', 'groundstation4'), ('instrument0', 'groundstation2'), ('instrument5', 'groundstation4'), ('instrument2', 'groundstation2'), ('instrument10', 'groundstation0'), ('instrument6', 'groundstation0'), ('instrument11', 'groundstation1'), ('instrument3', 'groundstation2'), ] )
rigid.on_board = set( [('instrument10', 'satellite4'), ('instrument4', 'satellite2'), ('instrument1', 'satellite0'), ('instrument0', 'satellite0'), ('instrument2', 'satellite0'), ('instrument9', 'satellite4'), ('instrument11', 'satellite5'), ('instrument7', 'satellite3'), ('instrument5', 'satellite2'), ('instrument3', 'satellite1'), ('instrument6', 'satellite2'), ('instrument8', 'satellite3'), ] )
state.power_avail = set( [('satellite2',), ('satellite0',), ('satellite3',), ('satellite1',), ('satellite4',), ('satellite5',), ] )
state.pointing = set( [('satellite4', 'planet15'), ('satellite2', 'groundstation2'), ('satellite5', 'phenomenon11'), ('satellite0', 'phenomenon12'), ('satellite3', 'groundstation4'), ('satellite1', 'groundstation1'), ] )
rigid.goal_pointing = set( [('satellite0', 'planet21'), ('satellite5', 'planet17'), ('satellite2', 'star14'), ] )
rigid.goal_have_image = set( [('star10', 'thermograph3'), ('star22', 'thermograph3'), ('star20', 'thermograph4'), ('planet8', 'image2'), ('planet21', 'thermograph0'), ('phenomenon18', 'image1'), ('phenomenon5', 'image1'), ('star14', 'thermograph4'), ('star9', 'thermograph0'), ('phenomenon13', 'image1'), ('star19', 'thermograph4'), ('planet23', 'image1'), ('phenomenon7', 'thermograph0'), ('planet17', 'image2'), ('planet15', 'image2'), ('phenomenon12', 'thermograph0'), ] )
state.power_on = set( [] )
state.calibrated = set( [] )
state.have_image = set( [] )

task_list = [('main',)]
