from ipyhop import State

state = State( 'init_state' )
rigid = State( 'rigid' )
rigid.object = {'instrument18', 'instrument2', 'satellite7', 'instrument7', 'instrument10', 'image1', 'planet7', 'phenomenon9', 'instrument8', 'planet23', 'instrument11', 'planet22', 'planet17', 'groundstation0', 'instrument15', 'instrument16', 'satellite0', 'star15', 'instrument0', 'instrument13', 'spectrograph2', 'planet14', 'planet20', 'star8', 'infrared0', 'planet21', 'instrument6', 'star12', 'phenomenon10', 'instrument1', 'phenomenon16', 'instrument9', 'instrument12', 'planet11', 'planet24', 'instrument14', 'thermograph3', 'satellite6', 'star13', 'satellite5', 'star3', 'instrument4', 'star1', 'instrument3', 'groundstation2', 'star19', 'star4', 'phenomenon5', 'star18', 'satellite2', 'satellite3', 'instrument5', 'instrument17', 'satellite1', 'thermograph4', 'satellite4', 'planet6'}
rigid.direction = {'planet11', 'planet24', 'planet7', 'phenomenon9', 'star13', 'star3', 'planet23', 'star1', 'planet22', 'groundstation0', 'groundstation2', 'star15', 'star19', 'star4', 'phenomenon5', 'star18', 'planet14', 'star8', 'planet21', 'star12', 'planet17', 'phenomenon10', 'planet20', 'phenomenon16', 'planet6'}
rigid.satellite = {'satellite2', 'satellite7', 'satellite3', 'satellite6', 'satellite5', 'satellite1', 'satellite0', 'satellite4'}
rigid.mode = {'infrared0', 'thermograph3', 'spectrograph2', 'image1', 'thermograph4'}
rigid.instrument = {'instrument18', 'instrument2', 'instrument14', 'instrument7', 'instrument10', 'instrument9', 'instrument8', 'instrument11', 'instrument4', 'instrument3', 'instrument15', 'instrument16', 'instrument0', 'instrument13', 'instrument5', 'instrument6', 'instrument17', 'instrument1', 'instrument12'}
rigid.supports = set( [('instrument17', 'spectrograph2'), ('instrument9', 'infrared0'), ('instrument7', 'spectrograph2'), ('instrument13', 'thermograph3'), ('instrument1', 'thermograph3'), ('instrument10', 'infrared0'), ('instrument10', 'thermograph4'), ('instrument6', 'spectrograph2'), ('instrument12', 'infrared0'), ('instrument4', 'thermograph4'), ('instrument0', 'image1'), ('instrument3', 'spectrograph2'), ('instrument13', 'infrared0'), ('instrument7', 'thermograph3'), ('instrument2', 'spectrograph2'), ('instrument5', 'thermograph3'), ('instrument0', 'thermograph4'), ('instrument5', 'image1'), ('instrument8', 'image1'), ('instrument5', 'infrared0'), ('instrument6', 'infrared0'), ('instrument3', 'image1'), ('instrument18', 'thermograph4'), ('instrument10', 'spectrograph2'), ('instrument4', 'spectrograph2'), ('instrument14', 'spectrograph2'), ('instrument16', 'thermograph4'), ('instrument15', 'thermograph4'), ('instrument1', 'spectrograph2'), ('instrument11', 'infrared0'), ('instrument4', 'thermograph3'), ] )
rigid.calibration_target = set( [('instrument11', 'groundstation0'), ('instrument2', 'star4'), ('instrument8', 'groundstation2'), ('instrument9', 'star3'), ('instrument5', 'groundstation2'), ('instrument6', 'groundstation2'), ('instrument16', 'groundstation2'), ('instrument3', 'groundstation2'), ('instrument10', 'groundstation0'), ('instrument4', 'star1'), ('instrument13', 'star3'), ('instrument1', 'star3'), ('instrument12', 'star1'), ('instrument0', 'groundstation0'), ('instrument7', 'star3'), ('instrument15', 'groundstation0'), ('instrument17', 'star1'), ('instrument14', 'groundstation2'), ('instrument18', 'star4'), ] )
rigid.on_board = set( [('instrument8', 'satellite4'), ('instrument3', 'satellite1'), ('instrument2', 'satellite1'), ('instrument6', 'satellite3'), ('instrument10', 'satellite5'), ('instrument4', 'satellite2'), ('instrument12', 'satellite5'), ('instrument1', 'satellite0'), ('instrument15', 'satellite6'), ('instrument0', 'satellite0'), ('instrument9', 'satellite4'), ('instrument17', 'satellite7'), ('instrument5', 'satellite2'), ('instrument18', 'satellite7'), ('instrument14', 'satellite6'), ('instrument16', 'satellite7'), ('instrument7', 'satellite4'), ('instrument13', 'satellite6'), ('instrument11', 'satellite5'), ] )
state.power_avail = set( [('satellite0',), ('satellite3',), ('satellite2',), ('satellite5',), ('satellite1',), ('satellite4',), ('satellite6',), ('satellite7',), ] )
state.pointing = set( [('satellite1', 'star18'), ('satellite4', 'phenomenon9'), ('satellite5', 'planet6'), ('satellite6', 'planet17'), ('satellite2', 'star19'), ('satellite0', 'star19'), ('satellite3', 'star4'), ('satellite7', 'planet11'), ] )
rigid.goal_pointing = set( [('satellite3', 'planet14'), ('satellite1', 'planet22'), ('satellite2', 'star13'), ('satellite5', 'planet24'), ('satellite7', 'star3'), ('satellite0', 'star19'), ] )
rigid.goal_have_image = set( [('planet21', 'infrared0'), ('star13', 'thermograph3'), ('phenomenon16', 'image1'), ('planet20', 'image1'), ('planet24', 'infrared0'), ('planet23', 'thermograph3'), ('star15', 'thermograph4'), ('star18', 'image1'), ('planet6', 'spectrograph2'), ('planet7', 'infrared0'), ('phenomenon10', 'image1'), ('phenomenon9', 'infrared0'), ('star12', 'thermograph3'), ('planet11', 'image1'), ('planet17', 'thermograph3'), ('planet14', 'thermograph4'), ('planet22', 'image1'), ('phenomenon5', 'spectrograph2'), ] )
state.calibrated = set( [] )
state.have_image = set( [] )
state.power_on = set( [] )

task_list = [('main',)]
