from ipyhop import State

from ordered_set import OrderedSet

state = State( 'init_state' )
rigid = State( 'rigid' )
rigid.object = OrderedSet(['instrument0', 'instrument1', 'instrument2', 'instrument3', 'instrument4', 'instrument5', 'instrument6', 'instrument7', 'instrument8', 'instrument9', 'instrument10', 'instrument11', 'instrument12', 'instrument13', 'instrument14', 'instrument15', 'instrument16', 'instrument17', 'instrument18', 'satellite0', 'satellite1', 'satellite2', 'satellite3', 'satellite4', 'satellite5', 'satellite6', 'satellite7', 'star3', 'groundstation0', 'groundstation2', 'star1', 'star4', 'phenomenon5', 'planet6', 'planet7', 'star8', 'phenomenon9', 'phenomenon10', 'planet11', 'star12', 'star13', 'planet14', 'star15', 'phenomenon16', 'planet17', 'star18', 'star19', 'planet20', 'planet21', 'planet22', 'planet23', 'planet24', 'image1', 'infrared0', 'thermograph3', 'spectrograph2', 'thermograph4'])
rigid.satellite = OrderedSet(['satellite0', 'satellite1', 'satellite2', 'satellite3', 'satellite4', 'satellite5', 'satellite6', 'satellite7'])
rigid.direction = OrderedSet(['star3', 'groundstation0', 'groundstation2', 'star1', 'star4', 'phenomenon5', 'planet6', 'planet7', 'star8', 'phenomenon9', 'phenomenon10', 'planet11', 'star12', 'star13', 'planet14', 'star15', 'phenomenon16', 'planet17', 'star18', 'star19', 'planet20', 'planet21', 'planet22', 'planet23', 'planet24'])
rigid.instrument = OrderedSet(['instrument0', 'instrument1', 'instrument2', 'instrument3', 'instrument4', 'instrument5', 'instrument6', 'instrument7', 'instrument8', 'instrument9', 'instrument10', 'instrument11', 'instrument12', 'instrument13', 'instrument14', 'instrument15', 'instrument16', 'instrument17', 'instrument18'])
rigid.mode = OrderedSet(['image1', 'infrared0', 'thermograph3', 'spectrograph2', 'thermograph4'])
rigid.supports = OrderedSet( [('instrument0', 'thermograph4'), ('instrument0', 'image1'), ('instrument1', 'spectrograph2'), ('instrument1', 'thermograph3'), ('instrument2', 'spectrograph2'), ('instrument3', 'image1'), ('instrument3', 'spectrograph2'), ('instrument4', 'thermograph3'), ('instrument4', 'thermograph4'), ('instrument4', 'spectrograph2'), ('instrument5', 'thermograph3'), ('instrument5', 'image1'), ('instrument5', 'infrared0'), ('instrument6', 'spectrograph2'), ('instrument6', 'infrared0'), ('instrument7', 'thermograph3'), ('instrument7', 'spectrograph2'), ('instrument8', 'image1'), ('instrument9', 'infrared0'), ('instrument10', 'thermograph4'), ('instrument10', 'spectrograph2'), ('instrument10', 'infrared0'), ('instrument11', 'infrared0'), ('instrument12', 'infrared0'), ('instrument13', 'thermograph3'), ('instrument13', 'infrared0'), ('instrument14', 'spectrograph2'), ('instrument15', 'thermograph4'), ('instrument16', 'thermograph4'), ('instrument17', 'spectrograph2'), ('instrument18', 'thermograph4'), ] )
rigid.calibration_target = OrderedSet( [('instrument0', 'groundstation0'), ('instrument1', 'star3'), ('instrument2', 'star4'), ('instrument3', 'groundstation2'), ('instrument4', 'star1'), ('instrument5', 'groundstation2'), ('instrument6', 'groundstation2'), ('instrument7', 'star3'), ('instrument8', 'groundstation2'), ('instrument9', 'star3'), ('instrument10', 'groundstation0'), ('instrument11', 'groundstation0'), ('instrument12', 'star1'), ('instrument13', 'star3'), ('instrument14', 'groundstation2'), ('instrument15', 'groundstation0'), ('instrument16', 'groundstation2'), ('instrument17', 'star1'), ('instrument18', 'star4'), ] )
rigid.on_board = OrderedSet( [('instrument0', 'satellite0'), ('instrument1', 'satellite0'), ('instrument2', 'satellite1'), ('instrument3', 'satellite1'), ('instrument4', 'satellite2'), ('instrument5', 'satellite2'), ('instrument6', 'satellite3'), ('instrument7', 'satellite4'), ('instrument8', 'satellite4'), ('instrument9', 'satellite4'), ('instrument10', 'satellite5'), ('instrument11', 'satellite5'), ('instrument12', 'satellite5'), ('instrument13', 'satellite6'), ('instrument14', 'satellite6'), ('instrument15', 'satellite6'), ('instrument16', 'satellite7'), ('instrument17', 'satellite7'), ('instrument18', 'satellite7'), ] )
state.power_avail = OrderedSet( [('satellite0',), ('satellite1',), ('satellite2',), ('satellite3',), ('satellite4',), ('satellite5',), ('satellite6',), ('satellite7',), ] )
state.pointing = OrderedSet( [('satellite0', 'star19'), ('satellite1', 'star18'), ('satellite2', 'star19'), ('satellite3', 'star4'), ('satellite4', 'phenomenon9'), ('satellite5', 'planet6'), ('satellite6', 'planet17'), ('satellite7', 'planet11'), ] )
rigid.goal_pointing = OrderedSet( [('satellite0', 'star19'), ('satellite1', 'planet22'), ('satellite2', 'star13'), ('satellite3', 'planet14'), ('satellite5', 'planet24'), ('satellite7', 'star3'), ] )
rigid.goal_have_image = OrderedSet( [('phenomenon5', 'spectrograph2'), ('planet6', 'spectrograph2'), ('planet7', 'infrared0'), ('phenomenon9', 'infrared0'), ('phenomenon10', 'image1'), ('planet11', 'image1'), ('star12', 'thermograph3'), ('star13', 'thermograph3'), ('planet14', 'thermograph4'), ('star15', 'thermograph4'), ('phenomenon16', 'image1'), ('planet17', 'thermograph3'), ('star18', 'image1'), ('planet20', 'image1'), ('planet21', 'infrared0'), ('planet22', 'image1'), ('planet23', 'thermograph3'), ('planet24', 'infrared0'), ] )
state.power_on = OrderedSet( [] )
state.calibrated = OrderedSet( [] )
state.have_image = OrderedSet( [] )

task_list = [('main',)]
