from ipyhop import State

state = State( 'init_state' )
rigid = State( 'rigid' )
rigid.object = {'star4', 'image1', 'groundstation2', 'star19', 'satellite0', 'planet14', 'star1', 'thermograph4', 'satellite4', 'satellite5', 'phenomenon10', 'star18', 'satellite6', 'planet23', 'planet7', 'phenomenon16', 'instrument3', 'planet24', 'phenomenon5', 'instrument1', 'infrared0', 'satellite2', 'star13', 'planet11', 'satellite1', 'instrument15', 'instrument4', 'instrument13', 'instrument11', 'instrument16', 'phenomenon9', 'star12', 'instrument17', 'planet6', 'groundstation0', 'star3', 'instrument2', 'instrument6', 'planet20', 'instrument9', 'instrument5', 'instrument7', 'instrument14', 'instrument18', 'planet22', 'satellite3', 'spectrograph2', 'star15', 'thermograph3', 'star8', 'instrument10', 'planet17', 'planet21', 'instrument0', 'satellite7', 'instrument8', 'instrument12'}
rigid.direction = {'star4', 'groundstation2', 'star19', 'planet6', 'planet14', 'groundstation0', 'star1', 'star3', 'planet20', 'planet22', 'phenomenon10', 'star18', 'planet23', 'planet7', 'phenomenon16', 'star15', 'star8', 'planet24', 'phenomenon5', 'planet17', 'planet21', 'star13', 'planet11', 'phenomenon9', 'star12'}
rigid.mode = {'image1', 'spectrograph2', 'thermograph4', 'infrared0', 'thermograph3'}
rigid.instrument = {'instrument17', 'instrument2', 'instrument6', 'instrument9', 'instrument5', 'instrument7', 'instrument14', 'instrument18', 'instrument3', 'instrument8', 'instrument12', 'instrument10', 'instrument1', 'instrument0', 'instrument15', 'instrument4', 'instrument13', 'instrument11', 'instrument16'}
rigid.satellite = {'satellite0', 'satellite4', 'satellite2', 'satellite5', 'satellite7', 'satellite6', 'satellite1', 'satellite3'}
rigid.supports = set( [('instrument3', 'spectrograph2'), ('instrument5', 'image1'), ('instrument4', 'thermograph3'), ('instrument9', 'infrared0'), ('instrument1', 'thermograph3'), ('instrument7', 'spectrograph2'), ('instrument6', 'spectrograph2'), ('instrument10', 'infrared0'), ('instrument5', 'infrared0'), ('instrument5', 'thermograph3'), ('instrument3', 'image1'), ('instrument4', 'spectrograph2'), ('instrument14', 'spectrograph2'), ('instrument8', 'image1'), ('instrument1', 'spectrograph2'), ('instrument4', 'thermograph4'), ('instrument17', 'spectrograph2'), ('instrument10', 'spectrograph2'), ('instrument13', 'infrared0'), ('instrument16', 'thermograph4'), ('instrument12', 'infrared0'), ('instrument2', 'spectrograph2'), ('instrument13', 'thermograph3'), ('instrument11', 'infrared0'), ('instrument0', 'thermograph4'), ('instrument10', 'thermograph4'), ('instrument6', 'infrared0'), ('instrument18', 'thermograph4'), ('instrument7', 'thermograph3'), ('instrument15', 'thermograph4'), ('instrument0', 'image1'), ] )
rigid.calibration_target = set( [('instrument3', 'groundstation2'), ('instrument8', 'groundstation2'), ('instrument18', 'star4'), ('instrument2', 'star4'), ('instrument6', 'groundstation2'), ('instrument10', 'groundstation0'), ('instrument13', 'star3'), ('instrument0', 'groundstation0'), ('instrument14', 'groundstation2'), ('instrument15', 'groundstation0'), ('instrument12', 'star1'), ('instrument16', 'groundstation2'), ('instrument7', 'star3'), ('instrument5', 'groundstation2'), ('instrument4', 'star1'), ('instrument9', 'star3'), ('instrument1', 'star3'), ('instrument11', 'groundstation0'), ('instrument17', 'star1'), ] )
rigid.on_board = set( [('instrument6', 'satellite3'), ('instrument0', 'satellite0'), ('instrument4', 'satellite2'), ('instrument13', 'satellite6'), ('instrument3', 'satellite1'), ('instrument5', 'satellite2'), ('instrument8', 'satellite4'), ('instrument14', 'satellite6'), ('instrument12', 'satellite5'), ('instrument7', 'satellite4'), ('instrument11', 'satellite5'), ('instrument16', 'satellite7'), ('instrument1', 'satellite0'), ('instrument15', 'satellite6'), ('instrument17', 'satellite7'), ('instrument9', 'satellite4'), ('instrument18', 'satellite7'), ('instrument2', 'satellite1'), ('instrument10', 'satellite5'), ] )
state.power_avail = set( [('satellite1',), ('satellite4',), ('satellite6',), ('satellite3',), ('satellite5',), ('satellite7',), ('satellite0',), ('satellite2',), ] )
state.pointing = set( [('satellite3', 'star4'), ('satellite4', 'phenomenon9'), ('satellite1', 'star18'), ('satellite6', 'planet17'), ('satellite2', 'star19'), ('satellite5', 'planet6'), ('satellite7', 'planet11'), ('satellite0', 'star19'), ] )
rigid.goal_pointing = set( [('satellite7', 'star3'), ('satellite3', 'planet14'), ('satellite2', 'star13'), ('satellite1', 'planet22'), ('satellite0', 'star19'), ('satellite5', 'planet24'), ] )
rigid.goal_have_image = set( [('phenomenon10', 'image1'), ('planet21', 'infrared0'), ('planet14', 'thermograph4'), ('planet11', 'image1'), ('phenomenon9', 'infrared0'), ('star18', 'image1'), ('planet6', 'spectrograph2'), ('planet23', 'thermograph3'), ('planet17', 'thermograph3'), ('phenomenon16', 'image1'), ('planet24', 'infrared0'), ('planet7', 'infrared0'), ('star12', 'thermograph3'), ('planet22', 'image1'), ('phenomenon5', 'spectrograph2'), ('star15', 'thermograph4'), ('star13', 'thermograph3'), ('planet20', 'image1'), ] )
state.calibrated = set( [] )
state.have_image = set( [] )
state.power_on = set( [] )

task_list = [('main',)]
