from ipyhop import State

from ordered_set import OrderedSet

state = State( 'init_state' )
rigid = State( 'rigid' )
rigid.object = OrderedSet(['instrument0', 'instrument1', 'instrument2', 'instrument3', 'instrument4', 'instrument5', 'instrument6', 'instrument7', 'instrument8', 'instrument9', 'instrument10', 'instrument11', 'instrument12', 'instrument13', 'instrument14', 'instrument15', 'instrument16', 'instrument17', 'instrument18', 'instrument19', 'instrument20', 'instrument21', 'instrument22', 'satellite0', 'satellite1', 'satellite2', 'satellite3', 'satellite4', 'satellite5', 'satellite6', 'satellite7', 'satellite8', 'satellite9', 'groundstation0', 'star3', 'groundstation4', 'star2', 'groundstation1', 'phenomenon5', 'planet6', 'planet7', 'planet8', 'phenomenon9', 'planet10', 'planet11', 'star12', 'star13', 'star14', 'star15', 'star16', 'phenomenon17', 'phenomenon18', 'planet19', 'star20', 'planet21', 'planet22', 'phenomenon23', 'star24', 'image0', 'image2', 'infrared4', 'thermograph1', 'spectrograph3'])
rigid.satellite = OrderedSet(['satellite0', 'satellite1', 'satellite2', 'satellite3', 'satellite4', 'satellite5', 'satellite6', 'satellite7', 'satellite8', 'satellite9'])
rigid.direction = OrderedSet(['groundstation0', 'star3', 'groundstation4', 'star2', 'groundstation1', 'phenomenon5', 'planet6', 'planet7', 'planet8', 'phenomenon9', 'planet10', 'planet11', 'star12', 'star13', 'star14', 'star15', 'star16', 'phenomenon17', 'phenomenon18', 'planet19', 'star20', 'planet21', 'planet22', 'phenomenon23', 'star24'])
rigid.instrument = OrderedSet(['instrument0', 'instrument1', 'instrument2', 'instrument3', 'instrument4', 'instrument5', 'instrument6', 'instrument7', 'instrument8', 'instrument9', 'instrument10', 'instrument11', 'instrument12', 'instrument13', 'instrument14', 'instrument15', 'instrument16', 'instrument17', 'instrument18', 'instrument19', 'instrument20', 'instrument21', 'instrument22'])
rigid.mode = OrderedSet(['image0', 'image2', 'infrared4', 'thermograph1', 'spectrograph3'])
rigid.supports = OrderedSet( [('instrument0', 'infrared4'), ('instrument1', 'spectrograph3'), ('instrument2', 'image0'), ('instrument2', 'thermograph1'), ('instrument2', 'image2'), ('instrument3', 'thermograph1'), ('instrument3', 'image0'), ('instrument4', 'image2'), ('instrument4', 'thermograph1'), ('instrument5', 'spectrograph3'), ('instrument5', 'thermograph1'), ('instrument5', 'image2'), ('instrument6', 'image0'), ('instrument7', 'infrared4'), ('instrument8', 'spectrograph3'), ('instrument9', 'image0'), ('instrument9', 'image2'), ('instrument9', 'thermograph1'), ('instrument10', 'image0'), ('instrument10', 'image2'), ('instrument10', 'spectrograph3'), ('instrument11', 'image0'), ('instrument12', 'infrared4'), ('instrument12', 'image0'), ('instrument13', 'spectrograph3'), ('instrument14', 'spectrograph3'), ('instrument14', 'thermograph1'), ('instrument14', 'image0'), ('instrument15', 'image0'), ('instrument15', 'thermograph1'), ('instrument15', 'image2'), ('instrument16', 'spectrograph3'), ('instrument16', 'image2'), ('instrument17', 'thermograph1'), ('instrument17', 'image2'), ('instrument17', 'image0'), ('instrument18', 'image2'), ('instrument18', 'thermograph1'), ('instrument19', 'thermograph1'), ('instrument19', 'infrared4'), ('instrument20', 'thermograph1'), ('instrument21', 'thermograph1'), ('instrument22', 'spectrograph3'), ('instrument22', 'thermograph1'), ('instrument22', 'infrared4'), ] )
rigid.calibration_target = OrderedSet( [('instrument0', 'star3'), ('instrument1', 'groundstation0'), ('instrument2', 'groundstation1'), ('instrument3', 'groundstation4'), ('instrument4', 'star3'), ('instrument5', 'groundstation4'), ('instrument6', 'groundstation1'), ('instrument7', 'star3'), ('instrument8', 'groundstation0'), ('instrument9', 'star3'), ('instrument10', 'star2'), ('instrument11', 'star3'), ('instrument12', 'groundstation4'), ('instrument13', 'star2'), ('instrument14', 'star3'), ('instrument15', 'groundstation4'), ('instrument16', 'groundstation0'), ('instrument17', 'groundstation4'), ('instrument18', 'star3'), ('instrument19', 'star2'), ('instrument20', 'groundstation4'), ('instrument21', 'star2'), ('instrument22', 'groundstation1'), ] )
rigid.on_board = OrderedSet( [('instrument0', 'satellite0'), ('instrument1', 'satellite0'), ('instrument2', 'satellite0'), ('instrument3', 'satellite1'), ('instrument4', 'satellite1'), ('instrument5', 'satellite1'), ('instrument6', 'satellite2'), ('instrument7', 'satellite3'), ('instrument8', 'satellite4'), ('instrument9', 'satellite4'), ('instrument10', 'satellite4'), ('instrument11', 'satellite5'), ('instrument12', 'satellite5'), ('instrument13', 'satellite5'), ('instrument14', 'satellite6'), ('instrument15', 'satellite6'), ('instrument16', 'satellite6'), ('instrument17', 'satellite7'), ('instrument18', 'satellite7'), ('instrument19', 'satellite8'), ('instrument20', 'satellite8'), ('instrument21', 'satellite8'), ('instrument22', 'satellite9'), ] )
state.power_avail = OrderedSet( [('satellite0',), ('satellite1',), ('satellite2',), ('satellite3',), ('satellite4',), ('satellite5',), ('satellite6',), ('satellite7',), ('satellite8',), ('satellite9',), ] )
state.pointing = OrderedSet( [('satellite0', 'star15'), ('satellite1', 'planet10'), ('satellite2', 'star24'), ('satellite3', 'phenomenon9'), ('satellite4', 'planet19'), ('satellite5', 'planet10'), ('satellite6', 'planet11'), ('satellite7', 'planet11'), ('satellite8', 'groundstation4'), ('satellite9', 'planet11'), ] )
rigid.goal_pointing = OrderedSet( [('satellite5', 'planet6'), ('satellite7', 'star3'), ('satellite8', 'star15'), ('satellite9', 'star16'), ] )
rigid.goal_have_image = OrderedSet( [('phenomenon5', 'thermograph1'), ('planet6', 'infrared4'), ('planet7', 'image0'), ('planet8', 'thermograph1'), ('phenomenon9', 'image2'), ('planet10', 'image0'), ('planet11', 'infrared4'), ('star12', 'image0'), ('star13', 'image0'), ('star14', 'thermograph1'), ('star15', 'image0'), ('star16', 'thermograph1'), ('phenomenon17', 'infrared4'), ('phenomenon18', 'spectrograph3'), ('star20', 'image0'), ('planet21', 'thermograph1'), ('planet22', 'image2'), ('phenomenon23', 'image0'), ('star24', 'infrared4'), ] )
state.power_on = OrderedSet( [] )
state.calibrated = OrderedSet( [] )
state.have_image = OrderedSet( [] )

task_list = [('main',)]
