from ipyhop import State

state = State( 'init_state' )
rigid = State( 'rigid' )
rigid.object = {'planet11', 'instrument8', 'satellite1', 'instrument9', 'instrument15', 'satellite10', 'satellite9', 'star1', 'planet13', 'planet16', 'planet6', 'star22', 'image4', 'satellite11', 'phenomenon24', 'instrument18', 'instrument17', 'phenomenon19', 'planet7', 'star3', 'phenomenon9', 'satellite0', 'image0', 'instrument4', 'instrument5', 'satellite3', 'thermograph1', 'instrument19', 'instrument3', 'instrument13', 'instrument12', 'instrument10', 'planet12', 'phenomenon23', 'star8', 'satellite8', 'instrument22', 'infrared2', 'groundstation0', 'instrument1', 'phenomenon14', 'instrument11', 'phenomenon15', 'satellite4', 'instrument7', 'phenomenon20', 'satellite2', 'groundstation2', 'planet5', 'satellite6', 'star21', 'star18', 'satellite7', 'satellite5', 'instrument0', 'infrared3', 'groundstation4', 'instrument2', 'instrument16', 'instrument20', 'instrument14', 'instrument21', 'instrument23', 'star10', 'phenomenon17', 'instrument6'}
rigid.instrument = {'instrument8', 'instrument22', 'instrument9', 'instrument15', 'instrument1', 'instrument11', 'instrument6', 'instrument7', 'instrument18', 'instrument17', 'instrument4', 'instrument5', 'instrument0', 'instrument2', 'instrument19', 'instrument3', 'instrument16', 'instrument13', 'instrument20', 'instrument12', 'instrument14', 'instrument10', 'instrument21', 'instrument23'}
rigid.direction = {'planet11', 'star8', 'groundstation0', 'phenomenon14', 'star1', 'planet13', 'planet16', 'planet6', 'phenomenon15', 'star22', 'phenomenon20', 'groundstation2', 'phenomenon24', 'planet5', 'phenomenon19', 'planet7', 'star21', 'star3', 'star18', 'phenomenon9', 'groundstation4', 'star10', 'phenomenon17', 'planet12', 'phenomenon23'}
rigid.mode = {'thermograph1', 'infrared2', 'image4', 'infrared3', 'image0'}
rigid.satellite = {'satellite6', 'satellite1', 'satellite8', 'satellite7', 'satellite10', 'satellite5', 'satellite0', 'satellite9', 'satellite3', 'satellite4', 'satellite11', 'satellite2'}
rigid.supports = set( [('instrument2', 'image0'), ('instrument21', 'image0'), ('instrument22', 'thermograph1'), ('instrument16', 'infrared2'), ('instrument15', 'thermograph1'), ('instrument10', 'image0'), ('instrument0', 'infrared3'), ('instrument8', 'image4'), ('instrument13', 'image4'), ('instrument17', 'infrared3'), ('instrument18', 'image4'), ('instrument15', 'image0'), ('instrument6', 'image0'), ('instrument7', 'image0'), ('instrument23', 'image4'), ('instrument1', 'infrared2'), ('instrument8', 'infrared2'), ('instrument18', 'infrared2'), ('instrument23', 'infrared2'), ('instrument23', 'thermograph1'), ('instrument18', 'thermograph1'), ('instrument16', 'image0'), ('instrument5', 'thermograph1'), ('instrument19', 'infrared3'), ('instrument1', 'image0'), ('instrument10', 'image4'), ('instrument2', 'thermograph1'), ('instrument8', 'image0'), ('instrument12', 'image4'), ('instrument21', 'thermograph1'), ('instrument4', 'infrared2'), ('instrument11', 'infrared2'), ('instrument4', 'infrared3'), ('instrument4', 'thermograph1'), ('instrument3', 'infrared2'), ('instrument14', 'infrared2'), ('instrument3', 'infrared3'), ('instrument14', 'thermograph1'), ('instrument6', 'infrared2'), ('instrument9', 'infrared3'), ('instrument20', 'infrared2'), ('instrument7', 'infrared3'), ] )
rigid.calibration_target = set( [('instrument19', 'groundstation4'), ('instrument9', 'star1'), ('instrument20', 'star1'), ('instrument16', 'star1'), ('instrument10', 'star3'), ('instrument3', 'groundstation4'), ('instrument2', 'groundstation0'), ('instrument15', 'groundstation4'), ('instrument5', 'groundstation4'), ('instrument4', 'groundstation2'), ('instrument13', 'star1'), ('instrument12', 'groundstation0'), ('instrument14', 'groundstation2'), ('instrument18', 'star1'), ('instrument6', 'groundstation2'), ('instrument7', 'groundstation0'), ('instrument22', 'groundstation0'), ('instrument8', 'groundstation4'), ('instrument21', 'star1'), ('instrument1', 'star3'), ('instrument0', 'groundstation0'), ('instrument17', 'groundstation0'), ('instrument23', 'star3'), ('instrument11', 'star1'), ] )
rigid.on_board = set( [('instrument6', 'satellite3'), ('instrument7', 'satellite3'), ('instrument17', 'satellite8'), ('instrument9', 'satellite4'), ('instrument22', 'satellite10'), ('instrument20', 'satellite10'), ('instrument4', 'satellite2'), ('instrument2', 'satellite1'), ('instrument13', 'satellite6'), ('instrument3', 'satellite2'), ('instrument10', 'satellite4'), ('instrument8', 'satellite3'), ('instrument5', 'satellite2'), ('instrument23', 'satellite11'), ('instrument0', 'satellite0'), ('instrument18', 'satellite9'), ('instrument19', 'satellite9'), ('instrument11', 'satellite5'), ('instrument12', 'satellite6'), ('instrument14', 'satellite6'), ('instrument15', 'satellite7'), ('instrument21', 'satellite10'), ('instrument1', 'satellite1'), ('instrument16', 'satellite8'), ] )
state.power_avail = set( [('satellite0',), ('satellite1',), ('satellite4',), ('satellite7',), ('satellite5',), ('satellite9',), ('satellite10',), ('satellite11',), ('satellite2',), ('satellite6',), ('satellite3',), ('satellite8',), ] )
state.pointing = set( [('satellite2', 'star21'), ('satellite7', 'planet12'), ('satellite8', 'phenomenon23'), ('satellite1', 'planet5'), ('satellite11', 'star8'), ('satellite9', 'phenomenon20'), ('satellite6', 'phenomenon20'), ('satellite10', 'star22'), ('satellite4', 'star22'), ('satellite3', 'star21'), ('satellite5', 'groundstation2'), ('satellite0', 'planet5'), ] )
rigid.goal_pointing = set( [('satellite4', 'phenomenon20'), ('satellite8', 'planet16'), ('satellite1', 'star22'), ] )
rigid.goal_have_image = set( [('phenomenon9', 'image4'), ('phenomenon24', 'infrared3'), ('star22', 'image4'), ('phenomenon14', 'infrared2'), ('planet7', 'image4'), ('phenomenon17', 'thermograph1'), ('phenomenon23', 'infrared3'), ('phenomenon15', 'infrared2'), ('star10', 'thermograph1'), ('planet16', 'infrared2'), ('planet6', 'image4'), ('planet11', 'image4'), ('planet13', 'infrared3'), ('planet5', 'image0'), ('star21', 'thermograph1'), ('planet12', 'thermograph1'), ('star18', 'image4'), ] )
state.calibrated = set( [] )
state.have_image = set( [] )
state.power_on = set( [] )

task_list = [('main',)]
