from ipyhop import State

from ordered_set import OrderedSet

state = State( 'init_state' )
rigid = State( 'rigid' )
rigid.object = OrderedSet(['instrument0', 'instrument1', 'instrument2', 'instrument3', 'instrument4', 'instrument5', 'instrument6', 'instrument7', 'instrument8', 'instrument9', 'instrument10', 'instrument11', 'instrument12', 'instrument13', 'instrument14', 'instrument15', 'instrument16', 'instrument17', 'instrument18', 'instrument19', 'instrument20', 'instrument21', 'instrument22', 'instrument23', 'satellite0', 'satellite1', 'satellite2', 'satellite3', 'satellite4', 'satellite5', 'satellite6', 'satellite7', 'satellite8', 'satellite9', 'satellite10', 'satellite11', 'groundstation2', 'groundstation4', 'star1', 'groundstation0', 'star3', 'planet5', 'planet6', 'planet7', 'star8', 'phenomenon9', 'star10', 'planet11', 'planet12', 'planet13', 'phenomenon14', 'phenomenon15', 'planet16', 'phenomenon17', 'star18', 'phenomenon19', 'phenomenon20', 'star21', 'star22', 'phenomenon23', 'phenomenon24', 'infrared3', 'image0', 'thermograph1', 'image4', 'infrared2'])
rigid.satellite = OrderedSet(['satellite0', 'satellite1', 'satellite2', 'satellite3', 'satellite4', 'satellite5', 'satellite6', 'satellite7', 'satellite8', 'satellite9', 'satellite10', 'satellite11'])
rigid.direction = OrderedSet(['groundstation2', 'groundstation4', 'star1', 'groundstation0', 'star3', 'planet5', 'planet6', 'planet7', 'star8', 'phenomenon9', 'star10', 'planet11', 'planet12', 'planet13', 'phenomenon14', 'phenomenon15', 'planet16', 'phenomenon17', 'star18', 'phenomenon19', 'phenomenon20', 'star21', 'star22', 'phenomenon23', 'phenomenon24'])
rigid.instrument = OrderedSet(['instrument0', 'instrument1', 'instrument2', 'instrument3', 'instrument4', 'instrument5', 'instrument6', 'instrument7', 'instrument8', 'instrument9', 'instrument10', 'instrument11', 'instrument12', 'instrument13', 'instrument14', 'instrument15', 'instrument16', 'instrument17', 'instrument18', 'instrument19', 'instrument20', 'instrument21', 'instrument22', 'instrument23'])
rigid.mode = OrderedSet(['infrared3', 'image0', 'thermograph1', 'image4', 'infrared2'])
rigid.supports = OrderedSet( [('instrument0', 'infrared3'), ('instrument1', 'image0'), ('instrument1', 'infrared2'), ('instrument2', 'thermograph1'), ('instrument2', 'image0'), ('instrument3', 'infrared3'), ('instrument3', 'infrared2'), ('instrument4', 'infrared3'), ('instrument4', 'infrared2'), ('instrument4', 'thermograph1'), ('instrument5', 'thermograph1'), ('instrument6', 'image0'), ('instrument6', 'infrared2'), ('instrument7', 'image0'), ('instrument7', 'infrared3'), ('instrument8', 'infrared2'), ('instrument8', 'image4'), ('instrument8', 'image0'), ('instrument9', 'infrared3'), ('instrument10', 'image4'), ('instrument10', 'image0'), ('instrument11', 'infrared2'), ('instrument12', 'image4'), ('instrument13', 'image4'), ('instrument14', 'thermograph1'), ('instrument14', 'infrared2'), ('instrument15', 'image0'), ('instrument15', 'thermograph1'), ('instrument16', 'image0'), ('instrument16', 'infrared2'), ('instrument17', 'infrared3'), ('instrument18', 'thermograph1'), ('instrument18', 'infrared2'), ('instrument18', 'image4'), ('instrument19', 'infrared3'), ('instrument20', 'infrared2'), ('instrument21', 'thermograph1'), ('instrument21', 'image0'), ('instrument22', 'thermograph1'), ('instrument23', 'infrared2'), ('instrument23', 'image4'), ('instrument23', 'thermograph1'), ] )
rigid.calibration_target = OrderedSet( [('instrument0', 'groundstation0'), ('instrument1', 'star3'), ('instrument2', 'groundstation0'), ('instrument3', 'groundstation4'), ('instrument4', 'groundstation2'), ('instrument5', 'groundstation4'), ('instrument6', 'groundstation2'), ('instrument7', 'groundstation0'), ('instrument8', 'groundstation4'), ('instrument9', 'star1'), ('instrument10', 'star3'), ('instrument11', 'star1'), ('instrument12', 'groundstation0'), ('instrument13', 'star1'), ('instrument14', 'groundstation2'), ('instrument15', 'groundstation4'), ('instrument16', 'star1'), ('instrument17', 'groundstation0'), ('instrument18', 'star1'), ('instrument19', 'groundstation4'), ('instrument20', 'star1'), ('instrument21', 'star1'), ('instrument22', 'groundstation0'), ('instrument23', 'star3'), ] )
rigid.on_board = OrderedSet( [('instrument0', 'satellite0'), ('instrument1', 'satellite1'), ('instrument2', 'satellite1'), ('instrument3', 'satellite2'), ('instrument4', 'satellite2'), ('instrument5', 'satellite2'), ('instrument6', 'satellite3'), ('instrument7', 'satellite3'), ('instrument8', 'satellite3'), ('instrument9', 'satellite4'), ('instrument10', 'satellite4'), ('instrument11', 'satellite5'), ('instrument12', 'satellite6'), ('instrument13', 'satellite6'), ('instrument14', 'satellite6'), ('instrument15', 'satellite7'), ('instrument16', 'satellite8'), ('instrument17', 'satellite8'), ('instrument18', 'satellite9'), ('instrument19', 'satellite9'), ('instrument20', 'satellite10'), ('instrument21', 'satellite10'), ('instrument22', 'satellite10'), ('instrument23', 'satellite11'), ] )
state.power_avail = OrderedSet( [('satellite0',), ('satellite1',), ('satellite2',), ('satellite3',), ('satellite4',), ('satellite5',), ('satellite6',), ('satellite7',), ('satellite8',), ('satellite9',), ('satellite10',), ('satellite11',), ] )
state.pointing = OrderedSet( [('satellite0', 'planet5'), ('satellite1', 'planet5'), ('satellite2', 'star21'), ('satellite3', 'star21'), ('satellite4', 'star22'), ('satellite5', 'groundstation2'), ('satellite6', 'phenomenon20'), ('satellite7', 'planet12'), ('satellite8', 'phenomenon23'), ('satellite9', 'phenomenon20'), ('satellite10', 'star22'), ('satellite11', 'star8'), ] )
rigid.goal_pointing = OrderedSet( [('satellite1', 'star22'), ('satellite4', 'phenomenon20'), ('satellite8', 'planet16'), ] )
rigid.goal_have_image = OrderedSet( [('planet5', 'image0'), ('planet6', 'image4'), ('planet7', 'image4'), ('phenomenon9', 'image4'), ('star10', 'thermograph1'), ('planet11', 'image4'), ('planet12', 'thermograph1'), ('planet13', 'infrared3'), ('phenomenon14', 'infrared2'), ('phenomenon15', 'infrared2'), ('planet16', 'infrared2'), ('phenomenon17', 'thermograph1'), ('star18', 'image4'), ('star21', 'thermograph1'), ('star22', 'image4'), ('phenomenon23', 'infrared3'), ('phenomenon24', 'infrared3'), ] )
state.power_on = OrderedSet( [] )
state.calibrated = OrderedSet( [] )
state.have_image = OrderedSet( [] )

task_list = [('main',)]
