from ipyhop import State

from ordered_set import OrderedSet

state = State( 'init_state' )
rigid = State( 'rigid' )
rigid.object = OrderedSet(['instrument0', 'instrument1', 'instrument2', 'instrument3', 'instrument4', 'instrument5', 'instrument6', 'instrument7', 'instrument8', 'instrument9', 'instrument10', 'instrument11', 'instrument12', 'instrument13', 'instrument14', 'instrument15', 'instrument16', 'instrument17', 'instrument18', 'instrument19', 'instrument20', 'instrument21', 'instrument22', 'instrument23', 'instrument24', 'satellite0', 'satellite1', 'satellite2', 'satellite3', 'satellite4', 'star1', 'groundstation4', 'star2', 'star3', 'groundstation0', 'phenomenon5', 'star6', 'phenomenon7', 'phenomenon8', 'planet9', 'star10', 'phenomenon11', 'star12', 'phenomenon13', 'star14', 'planet15', 'star16', 'planet17', 'star18', 'star19', 'phenomenon20', 'planet21', 'planet22', 'star23', 'phenomenon24', 'image4', 'spectrograph6', 'infrared2', 'image5', 'thermograph1', 'infrared7', 'spectrograph0', 'infrared3'])
rigid.satellite = OrderedSet(['satellite0', 'satellite1', 'satellite2', 'satellite3', 'satellite4'])
rigid.direction = OrderedSet(['star1', 'groundstation4', 'star2', 'star3', 'groundstation0', 'phenomenon5', 'star6', 'phenomenon7', 'phenomenon8', 'planet9', 'star10', 'phenomenon11', 'star12', 'phenomenon13', 'star14', 'planet15', 'star16', 'planet17', 'star18', 'star19', 'phenomenon20', 'planet21', 'planet22', 'star23', 'phenomenon24'])
rigid.instrument = OrderedSet(['instrument0', 'instrument1', 'instrument2', 'instrument3', 'instrument4', 'instrument5', 'instrument6', 'instrument7', 'instrument8', 'instrument9', 'instrument10', 'instrument11', 'instrument12', 'instrument13', 'instrument14', 'instrument15', 'instrument16', 'instrument17', 'instrument18', 'instrument19', 'instrument20', 'instrument21', 'instrument22', 'instrument23', 'instrument24'])
rigid.mode = OrderedSet(['image4', 'spectrograph6', 'infrared2', 'image5', 'thermograph1', 'infrared7', 'spectrograph0', 'infrared3'])
rigid.supports = OrderedSet( [('instrument0', 'infrared2'), ('instrument0', 'image4'), ('instrument1', 'spectrograph0'), ('instrument2', 'infrared3'), ('instrument2', 'thermograph1'), ('instrument2', 'spectrograph0'), ('instrument3', 'thermograph1'), ('instrument3', 'image5'), ('instrument4', 'spectrograph0'), ('instrument5', 'thermograph1'), ('instrument5', 'spectrograph0'), ('instrument5', 'spectrograph6'), ('instrument6', 'image5'), ('instrument6', 'infrared7'), ('instrument7', 'spectrograph6'), ('instrument7', 'thermograph1'), ('instrument7', 'spectrograph0'), ('instrument8', 'infrared3'), ('instrument8', 'infrared7'), ('instrument9', 'spectrograph0'), ('instrument10', 'image4'), ('instrument10', 'infrared7'), ('instrument10', 'image5'), ('instrument11', 'infrared2'), ('instrument12', 'thermograph1'), ('instrument13', 'infrared3'), ('instrument14', 'thermograph1'), ('instrument14', 'infrared2'), ('instrument15', 'infrared2'), ('instrument16', 'image4'), ('instrument16', 'spectrograph6'), ('instrument17', 'image4'), ('instrument17', 'infrared7'), ('instrument17', 'image5'), ('instrument18', 'image4'), ('instrument18', 'spectrograph6'), ('instrument19', 'infrared3'), ('instrument19', 'infrared7'), ('instrument19', 'spectrograph6'), ('instrument20', 'infrared3'), ('instrument20', 'infrared2'), ('instrument21', 'infrared2'), ('instrument21', 'thermograph1'), ('instrument22', 'thermograph1'), ('instrument22', 'image5'), ('instrument23', 'infrared7'), ('instrument23', 'thermograph1'), ('instrument24', 'infrared3'), ('instrument24', 'spectrograph0'), ] )
rigid.calibration_target = OrderedSet( [('instrument0', 'groundstation0'), ('instrument1', 'star3'), ('instrument2', 'star1'), ('instrument3', 'star1'), ('instrument4', 'star3'), ('instrument5', 'groundstation4'), ('instrument6', 'star3'), ('instrument7', 'star2'), ('instrument8', 'star1'), ('instrument9', 'star3'), ('instrument10', 'groundstation4'), ('instrument11', 'star2'), ('instrument12', 'star3'), ('instrument13', 'star2'), ('instrument14', 'groundstation4'), ('instrument15', 'star1'), ('instrument16', 'star2'), ('instrument17', 'groundstation0'), ('instrument18', 'star2'), ('instrument19', 'star3'), ('instrument20', 'star2'), ('instrument21', 'groundstation4'), ('instrument22', 'star2'), ('instrument23', 'star3'), ('instrument24', 'groundstation0'), ] )
rigid.on_board = OrderedSet( [('instrument0', 'satellite0'), ('instrument1', 'satellite0'), ('instrument2', 'satellite0'), ('instrument3', 'satellite1'), ('instrument4', 'satellite1'), ('instrument5', 'satellite1'), ('instrument6', 'satellite1'), ('instrument7', 'satellite1'), ('instrument8', 'satellite2'), ('instrument9', 'satellite2'), ('instrument10', 'satellite2'), ('instrument11', 'satellite2'), ('instrument12', 'satellite2'), ('instrument13', 'satellite2'), ('instrument14', 'satellite3'), ('instrument15', 'satellite3'), ('instrument16', 'satellite3'), ('instrument17', 'satellite3'), ('instrument18', 'satellite3'), ('instrument19', 'satellite3'), ('instrument20', 'satellite3'), ('instrument21', 'satellite3'), ('instrument22', 'satellite4'), ('instrument23', 'satellite4'), ('instrument24', 'satellite4'), ] )
state.power_avail = OrderedSet( [('satellite0',), ('satellite1',), ('satellite2',), ('satellite3',), ('satellite4',), ] )
state.pointing = OrderedSet( [('satellite0', 'planet21'), ('satellite1', 'planet21'), ('satellite2', 'phenomenon5'), ('satellite3', 'phenomenon20'), ('satellite4', 'star14'), ] )
rigid.goal_pointing = OrderedSet( [('satellite0', 'planet17'), ] )
rigid.goal_have_image = OrderedSet( [('phenomenon5', 'infrared7'), ('phenomenon5', 'image4'), ('phenomenon7', 'thermograph1'), ('planet9', 'spectrograph0'), ('planet9', 'spectrograph6'), ('star10', 'infrared3'), ('star10', 'spectrograph6'), ('phenomenon11', 'infrared2'), ('star12', 'spectrograph6'), ('star12', 'thermograph1'), ('phenomenon13', 'infrared7'), ('phenomenon13', 'infrared2'), ('star14', 'infrared2'), ('planet15', 'infrared2'), ('star16', 'image4'), ('planet17', 'image5'), ('planet17', 'image4'), ('star18', 'infrared2'), ('star19', 'infrared3'), ('star19', 'thermograph1'), ('phenomenon20', 'spectrograph0'), ('planet21', 'infrared3'), ('planet21', 'image5'), ('planet22', 'infrared2'), ('star23', 'infrared2'), ('phenomenon24', 'spectrograph6'), ('phenomenon24', 'image5'), ] )
state.power_on = OrderedSet( [] )
state.calibrated = OrderedSet( [] )
state.have_image = OrderedSet( [] )

task_list = [('main',)]
