from ipyhop import State

state = State( 'init_state' )
rigid = State( 'rigid' )
rigid.object = {'image4', 'planet17', 'star14', 'phenomenon5', 'image5', 'star2', 'instrument8', 'star3', 'planet22', 'instrument24', 'groundstation4', 'instrument15', 'star1', 'phenomenon7', 'instrument6', 'infrared2', 'instrument17', 'phenomenon20', 'instrument14', 'star19', 'star23', 'instrument5', 'satellite1', 'instrument3', 'phenomenon24', 'star10', 'instrument0', 'instrument12', 'instrument20', 'planet15', 'instrument23', 'infrared7', 'thermograph1', 'satellite2', 'instrument18', 'instrument2', 'spectrograph0', 'satellite3', 'satellite0', 'instrument4', 'planet9', 'instrument7', 'star16', 'instrument16', 'phenomenon11', 'instrument11', 'instrument9', 'planet21', 'phenomenon13', 'instrument21', 'phenomenon8', 'infrared3', 'groundstation0', 'instrument10', 'instrument13', 'star18', 'star12', 'instrument19', 'instrument22', 'instrument1', 'satellite4', 'spectrograph6', 'star6'}
rigid.satellite = {'satellite1', 'satellite0', 'satellite2', 'satellite4', 'satellite3'}
rigid.instrument = {'instrument0', 'instrument12', 'instrument20', 'instrument23', 'instrument18', 'instrument2', 'instrument8', 'instrument4', 'instrument24', 'instrument7', 'instrument15', 'instrument16', 'instrument11', 'instrument9', 'instrument6', 'instrument17', 'instrument21', 'instrument14', 'instrument10', 'instrument13', 'instrument5', 'instrument3', 'instrument19', 'instrument22', 'instrument1'}
rigid.mode = {'image4', 'infrared2', 'infrared7', 'thermograph1', 'infrared3', 'spectrograph0', 'image5', 'spectrograph6'}
rigid.direction = {'planet15', 'planet17', 'star14', 'phenomenon5', 'star2', 'star3', 'planet22', 'planet9', 'star16', 'groundstation4', 'star1', 'phenomenon11', 'phenomenon7', 'planet21', 'phenomenon13', 'phenomenon8', 'phenomenon20', 'star19', 'groundstation0', 'star23', 'star18', 'phenomenon24', 'star12', 'star10', 'star6'}
rigid.supports = set( [('instrument2', 'spectrograph0'), ('instrument19', 'spectrograph6'), ('instrument9', 'spectrograph0'), ('instrument8', 'infrared7'), ('instrument12', 'thermograph1'), ('instrument16', 'spectrograph6'), ('instrument4', 'spectrograph0'), ('instrument1', 'spectrograph0'), ('instrument2', 'thermograph1'), ('instrument13', 'infrared3'), ('instrument19', 'infrared7'), ('instrument24', 'infrared3'), ('instrument16', 'image4'), ('instrument21', 'thermograph1'), ('instrument22', 'thermograph1'), ('instrument17', 'image4'), ('instrument20', 'infrared2'), ('instrument8', 'infrared3'), ('instrument14', 'thermograph1'), ('instrument5', 'spectrograph0'), ('instrument17', 'infrared7'), ('instrument20', 'infrared3'), ('instrument0', 'image4'), ('instrument17', 'image5'), ('instrument24', 'spectrograph0'), ('instrument23', 'thermograph1'), ('instrument5', 'spectrograph6'), ('instrument3', 'thermograph1'), ('instrument22', 'image5'), ('instrument19', 'infrared3'), ('instrument15', 'infrared2'), ('instrument6', 'image5'), ('instrument5', 'thermograph1'), ('instrument18', 'spectrograph6'), ('instrument6', 'infrared7'), ('instrument2', 'infrared3'), ('instrument11', 'infrared2'), ('instrument23', 'infrared7'), ('instrument7', 'spectrograph0'), ('instrument10', 'image4'), ('instrument3', 'image5'), ('instrument21', 'infrared2'), ('instrument0', 'infrared2'), ('instrument7', 'spectrograph6'), ('instrument14', 'infrared2'), ('instrument18', 'image4'), ('instrument10', 'infrared7'), ('instrument10', 'image5'), ('instrument7', 'thermograph1'), ] )
rigid.calibration_target = set( [('instrument20', 'star2'), ('instrument7', 'star2'), ('instrument12', 'star3'), ('instrument19', 'star3'), ('instrument2', 'star1'), ('instrument5', 'groundstation4'), ('instrument15', 'star1'), ('instrument10', 'groundstation4'), ('instrument9', 'star3'), ('instrument16', 'star2'), ('instrument4', 'star3'), ('instrument1', 'star3'), ('instrument17', 'groundstation0'), ('instrument11', 'star2'), ('instrument6', 'star3'), ('instrument0', 'groundstation0'), ('instrument22', 'star2'), ('instrument3', 'star1'), ('instrument23', 'star3'), ('instrument13', 'star2'), ('instrument24', 'groundstation0'), ('instrument8', 'star1'), ('instrument18', 'star2'), ('instrument21', 'groundstation4'), ('instrument14', 'groundstation4'), ] )
rigid.on_board = set( [('instrument13', 'satellite2'), ('instrument19', 'satellite3'), ('instrument10', 'satellite2'), ('instrument24', 'satellite4'), ('instrument4', 'satellite1'), ('instrument16', 'satellite3'), ('instrument15', 'satellite3'), ('instrument8', 'satellite2'), ('instrument17', 'satellite3'), ('instrument2', 'satellite0'), ('instrument21', 'satellite3'), ('instrument6', 'satellite1'), ('instrument14', 'satellite3'), ('instrument12', 'satellite2'), ('instrument1', 'satellite0'), ('instrument3', 'satellite1'), ('instrument9', 'satellite2'), ('instrument5', 'satellite1'), ('instrument0', 'satellite0'), ('instrument11', 'satellite2'), ('instrument18', 'satellite3'), ('instrument22', 'satellite4'), ('instrument7', 'satellite1'), ('instrument23', 'satellite4'), ('instrument20', 'satellite3'), ] )
state.power_avail = set( [('satellite4',), ('satellite1',), ('satellite0',), ('satellite3',), ('satellite2',), ] )
state.pointing = set( [('satellite0', 'planet21'), ('satellite2', 'phenomenon5'), ('satellite1', 'planet21'), ('satellite4', 'star14'), ('satellite3', 'phenomenon20'), ] )
rigid.goal_pointing = set( [('satellite0', 'planet17'), ] )
rigid.goal_have_image = set( [('star19', 'infrared3'), ('phenomenon20', 'spectrograph0'), ('planet22', 'infrared2'), ('star10', 'spectrograph6'), ('phenomenon13', 'infrared2'), ('star12', 'spectrograph6'), ('star23', 'infrared2'), ('phenomenon24', 'spectrograph6'), ('star14', 'infrared2'), ('planet9', 'spectrograph0'), ('star12', 'thermograph1'), ('planet17', 'image4'), ('planet9', 'spectrograph6'), ('planet17', 'image5'), ('star18', 'infrared2'), ('star16', 'image4'), ('star19', 'thermograph1'), ('phenomenon24', 'image5'), ('planet15', 'infrared2'), ('planet21', 'image5'), ('phenomenon7', 'thermograph1'), ('star10', 'infrared3'), ('phenomenon11', 'infrared2'), ('phenomenon5', 'image4'), ('phenomenon13', 'infrared7'), ('planet21', 'infrared3'), ('phenomenon5', 'infrared7'), ] )
state.calibrated = set( [] )
state.have_image = set( [] )
state.power_on = set( [] )

task_list = [('main',)]
