from ipyhop import State

state = State( 'init_state' )
rigid = State( 'rigid' )
rigid.object = {'phenomenon14', 'star6', 'phenomenon21', 'instrument1', 'infrared5', 'planet22', 'instrument28', 'spectrograph6', 'star4', 'star10', 'star0', 'planet7', 'star2', 'star16', 'groundstation3', 'instrument15', 'instrument6', 'instrument19', 'image3', 'instrument24', 'instrument7', 'satellite0', 'instrument8', 'image4', 'phenomenon19', 'instrument17', 'instrument5', 'instrument0', 'instrument3', 'thermograph7', 'instrument2', 'instrument26', 'spectrograph0', 'instrument11', 'instrument4', 'planet15', 'instrument22', 'instrument12', 'satellite2', 'phenomenon8', 'instrument13', 'instrument14', 'planet18', 'instrument25', 'star24', 'star11', 'star20', 'infrared1', 'satellite1', 'satellite3', 'instrument10', 'groundstation1', 'image2', 'instrument21', 'planet9', 'instrument16', 'instrument9', 'thermograph8', 'planet13', 'star23', 'planet17', 'infrared9', 'phenomenon12', 'instrument18', 'instrument23', 'instrument20', 'instrument27', 'phenomenon5', 'satellite4'}
rigid.direction = {'phenomenon14', 'star6', 'phenomenon21', 'planet22', 'planet15', 'star4', 'phenomenon8', 'planet18', 'star10', 'star0', 'planet7', 'star24', 'star11', 'star2', 'star20', 'star16', 'groundstation3', 'groundstation1', 'planet9', 'planet13', 'star23', 'phenomenon19', 'planet17', 'phenomenon12', 'phenomenon5'}
rigid.mode = {'thermograph7', 'image2', 'infrared5', 'spectrograph0', 'image3', 'spectrograph6', 'thermograph8', 'image4', 'infrared9', 'infrared1'}
rigid.satellite = {'satellite2', 'satellite4', 'satellite1', 'satellite3', 'satellite0'}
rigid.instrument = {'instrument0', 'instrument3', 'instrument5', 'instrument1', 'instrument26', 'instrument11', 'instrument4', 'instrument22', 'instrument28', 'instrument12', 'instrument13', 'instrument14', 'instrument25', 'instrument10', 'instrument15', 'instrument6', 'instrument23', 'instrument19', 'instrument21', 'instrument24', 'instrument7', 'instrument16', 'instrument9', 'instrument8', 'instrument18', 'instrument17', 'instrument20', 'instrument27', 'instrument2'}
rigid.supports = set( [('instrument23', 'image3'), ('instrument5', 'infrared9'), ('instrument16', 'image2'), ('instrument2', 'image4'), ('instrument27', 'image2'), ('instrument20', 'image4'), ('instrument28', 'image4'), ('instrument2', 'thermograph8'), ('instrument8', 'infrared9'), ('instrument13', 'infrared1'), ('instrument22', 'infrared5'), ('instrument6', 'infrared1'), ('instrument28', 'thermograph7'), ('instrument10', 'spectrograph6'), ('instrument12', 'thermograph8'), ('instrument7', 'spectrograph6'), ('instrument3', 'infrared9'), ('instrument17', 'infrared5'), ('instrument15', 'thermograph7'), ('instrument21', 'thermograph8'), ('instrument26', 'image3'), ('instrument8', 'spectrograph0'), ('instrument24', 'thermograph8'), ('instrument11', 'image4'), ('instrument11', 'infrared1'), ('instrument20', 'image3'), ('instrument5', 'image4'), ('instrument21', 'infrared5'), ('instrument11', 'thermograph7'), ('instrument9', 'thermograph7'), ('instrument4', 'thermograph8'), ('instrument22', 'thermograph8'), ('instrument18', 'infrared9'), ('instrument23', 'thermograph8'), ('instrument12', 'infrared9'), ('instrument21', 'image3'), ('instrument0', 'image3'), ('instrument10', 'infrared1'), ('instrument19', 'infrared5'), ('instrument1', 'infrared9'), ('instrument12', 'infrared5'), ('instrument8', 'thermograph7'), ('instrument27', 'infrared9'), ('instrument2', 'image2'), ('instrument20', 'image2'), ('instrument25', 'infrared5'), ('instrument19', 'image2'), ('instrument10', 'thermograph8'), ('instrument16', 'infrared9'), ('instrument13', 'image2'), ('instrument14', 'image3'), ('instrument28', 'spectrograph0'), ('instrument7', 'thermograph8'), ('instrument4', 'image3'), ] )
rigid.calibration_target = set( [('instrument1', 'star4'), ('instrument7', 'groundstation1'), ('instrument16', 'star4'), ('instrument19', 'groundstation3'), ('instrument12', 'groundstation3'), ('instrument6', 'groundstation3'), ('instrument27', 'groundstation3'), ('instrument9', 'star4'), ('instrument20', 'groundstation1'), ('instrument22', 'star4'), ('instrument28', 'groundstation1'), ('instrument18', 'groundstation1'), ('instrument11', 'groundstation3'), ('instrument15', 'star2'), ('instrument14', 'groundstation3'), ('instrument5', 'groundstation3'), ('instrument21', 'star2'), ('instrument0', 'star2'), ('instrument25', 'star2'), ('instrument4', 'groundstation3'), ('instrument10', 'star4'), ('instrument24', 'star2'), ('instrument17', 'star0'), ('instrument23', 'star2'), ('instrument26', 'star4'), ('instrument3', 'star0'), ('instrument2', 'star4'), ('instrument8', 'star2'), ('instrument13', 'star4'), ] )
rigid.on_board = set( [('instrument6', 'satellite0'), ('instrument12', 'satellite1'), ('instrument0', 'satellite0'), ('instrument19', 'satellite2'), ('instrument1', 'satellite0'), ('instrument18', 'satellite2'), ('instrument15', 'satellite1'), ('instrument26', 'satellite4'), ('instrument20', 'satellite3'), ('instrument16', 'satellite2'), ('instrument5', 'satellite0'), ('instrument9', 'satellite0'), ('instrument4', 'satellite0'), ('instrument14', 'satellite1'), ('instrument21', 'satellite3'), ('instrument11', 'satellite1'), ('instrument28', 'satellite4'), ('instrument8', 'satellite0'), ('instrument27', 'satellite4'), ('instrument24', 'satellite4'), ('instrument25', 'satellite4'), ('instrument7', 'satellite0'), ('instrument10', 'satellite1'), ('instrument3', 'satellite0'), ('instrument17', 'satellite2'), ('instrument22', 'satellite4'), ('instrument23', 'satellite4'), ('instrument2', 'satellite0'), ('instrument13', 'satellite1'), ] )
state.power_avail = set( [('satellite1',), ('satellite4',), ('satellite2',), ('satellite0',), ('satellite3',), ] )
state.pointing = set( [('satellite1', 'phenomenon19'), ('satellite2', 'phenomenon14'), ('satellite3', 'star10'), ('satellite0', 'groundstation1'), ('satellite4', 'star16'), ] )
rigid.goal_pointing = set( [('satellite1', 'phenomenon19'), ] )
rigid.goal_have_image = set( [('star16', 'image4'), ('star23', 'image2'), ('star6', 'image3'), ('phenomenon12', 'image4'), ('star6', 'spectrograph6'), ('planet22', 'image2'), ('planet7', 'spectrograph6'), ('star24', 'spectrograph6'), ('phenomenon21', 'image2'), ('planet7', 'infrared5'), ('phenomenon19', 'image2'), ('phenomenon5', 'spectrograph0'), ('star24', 'infrared5'), ('planet18', 'infrared9'), ('star11', 'image3'), ('planet7', 'image2'), ('star6', 'spectrograph0'), ('phenomenon8', 'thermograph7'), ('planet18', 'infrared5'), ('planet13', 'spectrograph6'), ('phenomenon21', 'image4'), ('star16', 'image3'), ('planet13', 'infrared5'), ('planet15', 'image3'), ('phenomenon19', 'image4'), ('star20', 'spectrograph0'), ('phenomenon21', 'thermograph7'), ('planet13', 'image2'), ('phenomenon14', 'thermograph7'), ('phenomenon5', 'thermograph8'), ('star10', 'spectrograph6'), ('planet9', 'spectrograph6'), ('star23', 'infrared9'), ('phenomenon8', 'spectrograph6'), ('planet18', 'thermograph7'), ('star11', 'image4'), ('planet22', 'spectrograph6'), ('phenomenon8', 'infrared5'), ('phenomenon5', 'image3'), ('star11', 'thermograph7'), ] )
state.power_on = set( [] )
state.have_image = set( [] )
state.calibrated = set( [] )

task_list = [('main',)]
