from ipyhop import State

from ordered_set import OrderedSet

state = State( 'init_state' )
rigid = State( 'rigid' )
rigid.object = OrderedSet(['instrument0', 'instrument1', 'instrument2', 'instrument3', 'instrument4', 'instrument5', 'instrument6', 'instrument7', 'instrument8', 'instrument9', 'instrument10', 'instrument11', 'instrument12', 'instrument13', 'instrument14', 'instrument15', 'instrument16', 'instrument17', 'instrument18', 'instrument19', 'instrument20', 'instrument21', 'instrument22', 'instrument23', 'instrument24', 'instrument25', 'instrument26', 'instrument27', 'instrument28', 'satellite0', 'satellite1', 'satellite2', 'satellite3', 'satellite4', 'star0', 'star2', 'star4', 'groundstation3', 'groundstation1', 'phenomenon5', 'star6', 'planet7', 'phenomenon8', 'planet9', 'star10', 'star11', 'phenomenon12', 'planet13', 'phenomenon14', 'planet15', 'star16', 'planet17', 'planet18', 'phenomenon19', 'star20', 'phenomenon21', 'planet22', 'star23', 'star24', 'spectrograph6', 'infrared1', 'thermograph8', 'infrared5', 'image3', 'infrared9', 'image2', 'thermograph7', 'image4', 'spectrograph0'])
rigid.satellite = OrderedSet(['satellite0', 'satellite1', 'satellite2', 'satellite3', 'satellite4'])
rigid.direction = OrderedSet(['star0', 'star2', 'star4', 'groundstation3', 'groundstation1', 'phenomenon5', 'star6', 'planet7', 'phenomenon8', 'planet9', 'star10', 'star11', 'phenomenon12', 'planet13', 'phenomenon14', 'planet15', 'star16', 'planet17', 'planet18', 'phenomenon19', 'star20', 'phenomenon21', 'planet22', 'star23', 'star24'])
rigid.instrument = OrderedSet(['instrument0', 'instrument1', 'instrument2', 'instrument3', 'instrument4', 'instrument5', 'instrument6', 'instrument7', 'instrument8', 'instrument9', 'instrument10', 'instrument11', 'instrument12', 'instrument13', 'instrument14', 'instrument15', 'instrument16', 'instrument17', 'instrument18', 'instrument19', 'instrument20', 'instrument21', 'instrument22', 'instrument23', 'instrument24', 'instrument25', 'instrument26', 'instrument27', 'instrument28'])
rigid.mode = OrderedSet(['spectrograph6', 'infrared1', 'thermograph8', 'infrared5', 'image3', 'infrared9', 'image2', 'thermograph7', 'image4', 'spectrograph0'])
rigid.supports = OrderedSet( [('instrument0', 'image3'), ('instrument1', 'infrared9'), ('instrument2', 'thermograph8'), ('instrument2', 'image2'), ('instrument2', 'image4'), ('instrument3', 'infrared9'), ('instrument4', 'image3'), ('instrument4', 'thermograph8'), ('instrument5', 'infrared9'), ('instrument5', 'image4'), ('instrument6', 'infrared1'), ('instrument7', 'thermograph8'), ('instrument7', 'spectrograph6'), ('instrument8', 'spectrograph0'), ('instrument8', 'infrared9'), ('instrument8', 'thermograph7'), ('instrument9', 'thermograph7'), ('instrument10', 'infrared1'), ('instrument10', 'thermograph8'), ('instrument10', 'spectrograph6'), ('instrument11', 'image4'), ('instrument11', 'thermograph7'), ('instrument11', 'infrared1'), ('instrument12', 'infrared9'), ('instrument12', 'thermograph8'), ('instrument12', 'infrared5'), ('instrument13', 'image2'), ('instrument13', 'infrared1'), ('instrument14', 'image3'), ('instrument15', 'thermograph7'), ('instrument16', 'infrared9'), ('instrument16', 'image2'), ('instrument17', 'infrared5'), ('instrument18', 'infrared9'), ('instrument19', 'infrared5'), ('instrument19', 'image2'), ('instrument20', 'image2'), ('instrument20', 'image3'), ('instrument20', 'image4'), ('instrument21', 'image3'), ('instrument21', 'thermograph8'), ('instrument21', 'infrared5'), ('instrument22', 'thermograph8'), ('instrument22', 'infrared5'), ('instrument23', 'thermograph8'), ('instrument23', 'image3'), ('instrument24', 'thermograph8'), ('instrument25', 'infrared5'), ('instrument26', 'image3'), ('instrument27', 'image2'), ('instrument27', 'infrared9'), ('instrument28', 'spectrograph0'), ('instrument28', 'image4'), ('instrument28', 'thermograph7'), ] )
rigid.calibration_target = OrderedSet( [('instrument0', 'star2'), ('instrument1', 'star4'), ('instrument2', 'star4'), ('instrument3', 'star0'), ('instrument4', 'groundstation3'), ('instrument5', 'groundstation3'), ('instrument6', 'groundstation3'), ('instrument7', 'groundstation1'), ('instrument8', 'star2'), ('instrument9', 'star4'), ('instrument10', 'star4'), ('instrument11', 'groundstation3'), ('instrument12', 'groundstation3'), ('instrument13', 'star4'), ('instrument14', 'groundstation3'), ('instrument15', 'star2'), ('instrument16', 'star4'), ('instrument17', 'star0'), ('instrument18', 'groundstation1'), ('instrument19', 'groundstation3'), ('instrument20', 'groundstation1'), ('instrument21', 'star2'), ('instrument22', 'star4'), ('instrument23', 'star2'), ('instrument24', 'star2'), ('instrument25', 'star2'), ('instrument26', 'star4'), ('instrument27', 'groundstation3'), ('instrument28', 'groundstation1'), ] )
rigid.on_board = OrderedSet( [('instrument0', 'satellite0'), ('instrument1', 'satellite0'), ('instrument2', 'satellite0'), ('instrument3', 'satellite0'), ('instrument4', 'satellite0'), ('instrument5', 'satellite0'), ('instrument6', 'satellite0'), ('instrument7', 'satellite0'), ('instrument8', 'satellite0'), ('instrument9', 'satellite0'), ('instrument10', 'satellite1'), ('instrument11', 'satellite1'), ('instrument12', 'satellite1'), ('instrument13', 'satellite1'), ('instrument14', 'satellite1'), ('instrument15', 'satellite1'), ('instrument16', 'satellite2'), ('instrument17', 'satellite2'), ('instrument18', 'satellite2'), ('instrument19', 'satellite2'), ('instrument20', 'satellite3'), ('instrument21', 'satellite3'), ('instrument22', 'satellite4'), ('instrument23', 'satellite4'), ('instrument24', 'satellite4'), ('instrument25', 'satellite4'), ('instrument26', 'satellite4'), ('instrument27', 'satellite4'), ('instrument28', 'satellite4'), ] )
state.power_avail = OrderedSet( [('satellite0',), ('satellite1',), ('satellite2',), ('satellite3',), ('satellite4',), ] )
state.pointing = OrderedSet( [('satellite0', 'groundstation1'), ('satellite1', 'phenomenon19'), ('satellite2', 'phenomenon14'), ('satellite3', 'star10'), ('satellite4', 'star16'), ] )
rigid.goal_pointing = OrderedSet( [('satellite1', 'phenomenon19'), ] )
rigid.goal_have_image = OrderedSet( [('phenomenon5', 'thermograph8'), ('phenomenon5', 'spectrograph0'), ('phenomenon5', 'image3'), ('star6', 'spectrograph0'), ('star6', 'spectrograph6'), ('star6', 'image3'), ('planet7', 'spectrograph6'), ('planet7', 'infrared5'), ('planet7', 'image2'), ('phenomenon8', 'spectrograph6'), ('phenomenon8', 'infrared5'), ('phenomenon8', 'thermograph7'), ('planet9', 'spectrograph6'), ('star10', 'spectrograph6'), ('star11', 'thermograph7'), ('star11', 'image4'), ('star11', 'image3'), ('phenomenon12', 'image4'), ('planet13', 'infrared5'), ('planet13', 'spectrograph6'), ('planet13', 'image2'), ('phenomenon14', 'thermograph7'), ('planet15', 'image3'), ('star16', 'image3'), ('star16', 'image4'), ('planet18', 'infrared9'), ('planet18', 'infrared5'), ('planet18', 'thermograph7'), ('phenomenon19', 'image2'), ('phenomenon19', 'image4'), ('star20', 'spectrograph0'), ('phenomenon21', 'image4'), ('phenomenon21', 'image2'), ('phenomenon21', 'thermograph7'), ('planet22', 'image2'), ('planet22', 'spectrograph6'), ('star23', 'image2'), ('star23', 'infrared9'), ('star24', 'spectrograph6'), ('star24', 'infrared5'), ] )
state.power_on = OrderedSet( [] )
state.calibrated = OrderedSet( [] )
state.have_image = OrderedSet( [] )

task_list = [('main',)]
